api/revanced-patches.api, src/main/kotlin/app/revanced/patches/youtube/interaction/copyvideourl/CopyVideoUrlResourcePatch.kt, src/main/kotlin/app/revanced/patches/youtube/interaction/downloads/ExternalDownloadsResourcePatch.kt, src/main/kotlin/app/revanced/patches/youtube/misc/playercontrols/BottomControlsResourcePatch.kt
…Patch` patch public
Motivation: Allows third party patch bundles to add controls to bottom controls bar
=> feat(Public API): Make `BottomControlsResource#addControls` public

src/main/kotlin/app/revanced/patches/youtube/layout/theme/ThemeBytecodePatch.kt
Add the old dark color (#212121) which was used in YT 16.xx.xx - v17.xx.xx
Or is there a more appropriate name? I also considered the name "Dark gray"
=> feat(YouTube - Theme): Add classic dark color to presets

src/main/resources/addresources/values/arrays.xml, src/main/resources/addresources/values/strings.xml
YouTube is disabling versions below v18 now and spoofing to these versions will break the app.
Maybe integrations can bump to newer versions, if currently users have set it below v18
=> fix(YouTube - Spoof app version): Remove broken versions

src/main/resources/addresources/values/arrays.xml, src/main/resources/addresources/values/strings.xml
https://github.com/ReVanced/revanced-patches/pull/2776#issuecomment-1971906647
Based on this discussion, add several versions from [inotia00's fork](https://github.com/inotia00/revanced-patches/blob/revanced-extended/src/main/resources/youtube/settings/host/values/strings.xml#L803-L810).
- ~~`18.48.39` - Disable real-time updating \'views\' and \'likes\' counts (inotia00's one was 18.40.34, but I tested and it seems 18.48 now)~~
- ~~`18.05.40` - Restore old comment input box (This might be helpful for users who have keyboard hang up issue)~~
- `17.41.37` - Restore old playlist shelf [[image]](https://private-user-images.githubusercontent.com/90930406/308934323-01a818ea-79ab-45ec-885a-b0711850552f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1Y …
=> feat(YouTube - Spoof app version): Add target versions

api/revanced-patches.api, src/main/kotlin/app/revanced/patches/music/misc/gms/GmsCoreSupportPatch.kt, src/main/kotlin/app/revanced/patches/shared/misc/gms/BaseGmsCoreSupportPatch.kt, src/main/kotlin/app/revanced/patches/shared/misc/gms/BaseGmsCoreSupportResourcePatch.kt, src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/ClientSpoofPatch.kt, src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/SpoofSignaturePatch.kt, src/main/kotlin/app/revanced/patches/youtube/misc/gms/GmsCoreSupportPatch.kt, src/main/kotlin/app/revanced/patches/youtube/misc/gms/GmsCoreSupportResourcePatch.kt, src/main/resources/addresources/values/strings.xml
This PR switches to the ReVanced GmsCore vendor to fix playback issues. The previous vendor did not update GmsCore, resulting in missing features required for playback, specifically PoToken, which was added to requests recently. Because the PoToken was missing, playback failed.
Related:
- https://github.com/microg/GmsCore/issues/1870
- https://github.com/microg/GmsCore/issues/2253
Fixes #293
Depends on:
- https://github.com/ReVanced/GmsCore/pull/2
=> fix(YouTube): Fix video playback by switching to ReVanced GmsCore vendor

api/revanced-patches.api, src/main/kotlin/app/revanced/patches/music/misc/gms/GmsCoreSupportPatch.kt, src/main/kotlin/app/revanced/patches/shared/misc/gms/BaseGmsCoreSupportPatch.kt, src/main/kotlin/app/revanced/patches/shared/misc/gms/BaseGmsCoreSupportResourcePatch.kt, src/main/kotlin/app/revanced/patches/shared/misc/gms/fingerprints/GmsCoreSupportFingerprint.kt, src/main/kotlin/app/revanced/patches/youtube/misc/announcements/AnnouncementsPatch.kt, src/main/kotlin/app/revanced/patches/youtube/misc/gms/GmsCoreSupportPatch.kt, src/main/kotlin/app/revanced/patches/youtube/shared/fingerprints/MainActivityOnCreateFingerprint.kt, src/main/resources/addresources/values/strings.xml
This PR requests the user to disable or ignore battery optimizations for GmsCore. This is necessary to prevent playback from failing when GmsCore is killed in the background. It is also a suggested action by GmsCore itself.
One bug that I have been observing for a while is that, for some reason, the app is not correctly killed with `System.exit(0)`. This causes spam; for example, in WSA this launches the website multiple times repeatedly in an infinite loop. Offtopic though.
RE: https://github.com/ReVanced/revanced-integrations/pull/599
=> feat(YouTube - GmsCore): Require ignoring battery optimizations

src/main/kotlin/app/revanced/patches/tumblr/annoyances/popups/fingerprints/ShowGiftMessagePopupFingerprint.kt, src/main/kotlin/app/revanced/patches/tumblr/featureflags/OverrideFeatureFlagsPatch.kt, src/main/kotlin/app/revanced/patches/tumblr/featureflags/fingerprints/GetFeatureValueFingerprint.kt, src/main/kotlin/app/revanced/patches/tumblr/live/DisableTumblrLivePatch.kt
Due to more classes getting obfuscated in new app versions, two patches had to be fixed:
- fixed feature flags patch & fingerprint
- fixed gift message popup fingerprint
Due to the removal of Tumblr Live, the Disable Tumblr Live Patch is obsolete
- deprecated disable tumblr live patch
=> fix(Tumblr): Restore compatibility with latest versions 

api/revanced-patches.api, src/main/kotlin/app/revanced/patches/tumblr/fixes/FixOldVersionsPatch.kt, src/main/kotlin/app/revanced/patches/tumblr/fixes/fingerprints/AddQueryParamFingerprint.kt, src/main/kotlin/app/revanced/patches/tumblr/fixes/fingerprints/HttpPathParserFingerprint.kt
The old `Fix old versions` patch still left some requests broken for two reasons:
- there was another broken field being requested: `?live_streaming_user_id`
- the requested fields were sometimes not specified directly in on the endpoint function (but instead supplied as a parameter with the @\Query annotation)
These issues are now resolved
- Patch now removes `,?live_streaming_user_id` from URLs as well
- added additional injection into retrofit2 [RequestBuilder.addQueryParam](https://github.com/square/retrofit/blob/trunk/retrofit/src/main/java/retrofit2/RequestBuilder.java#L186) to remove blocked fields even when not directly specified in the request path
=> fix(Tumblr - Fix old versions): Improve reliability by removing remnances of Tumblr Live 

api/revanced-patches.api, src/main/kotlin/app/revanced/patches/amazon/deeplinking/DeepLinkingFingerprint.kt, src/main/kotlin/app/revanced/patches/amazon/deeplinking/DeepLinkingPatch.kt
Amazon's mobile app (`com.amazon.mShop.android.shopping`) disables its deep-linking activity in certain cases (when it is not set to open its links by default), preventing it from being launched even via an explicit Intent.
This patch removes that restriction.
=> feat(Amazon): Add `Always allow deep-linking` patch

api/revanced-patches.api, src/main/kotlin/app/revanced/patches/twitter/misc/links/SanitizeSharingLinksPatch.kt, src/main/kotlin/app/revanced/patches/twitter/misc/links/fingerprints/SanitizeSharingLinksFingerprint.kt
The Twitter (X) app appends some tracking query parameters to shared links, this patch removes them.  
From decompiler, before:
After:
=> feat(Twitter): Add `Sanitize sharing links` patch

api/revanced-patches.api, src/main/kotlin/app/revanced/patches/all/misc/hex/HexPatch.kt, src/main/kotlin/app/revanced/patches/shared/misc/hex/BaseHexPatch.kt
This PR adds a patch to make replacements given a byte pattern in an APK path with another byte pattern. It'll be the basis for other patches that need replacements in native binaries, for example.
-  [x] Currently, this patch is standalone, so other patches can't really depend on it to make fixed hex patches
=> feat: Add `Hex` patch

src/main/kotlin/app/revanced/patches/music/layout/upgradebutton/fingerprints/PivotBarConstructorFingerprint.kt
=> fix(YouTube Music - Remove upgrade button): Fix compatibility with latest versions

src/main/kotlin/app/revanced/patches/photomath/detection/deviceid/SpoofDeviceIdPatch.kt, src/main/kotlin/app/revanced/patches/photomath/detection/deviceid/fingerprints/GetDeviceIdFingerprint.kt, src/main/kotlin/app/revanced/patches/photomath/detection/signature/fingerprints/CheckSignatureFingerprint.kt, src/main/kotlin/app/revanced/patches/photomath/misc/annoyances/HideUpdatePopupPatch.kt, src/main/kotlin/app/revanced/patches/photomath/misc/unlock/plus/UnlockPlusPatch.kt
Fixed CheckSignatureFingerprint and GetDeviceIdFingerprint 
Changed supported version from `8.32.0` to `8.37.0`
=> feat(Photomath): Support version `8.37.0`

src/main/kotlin/app/revanced/patches/music/layout/premium/fingerprints/HideGetPremiumFingerprint.kt, src/main/kotlin/app/revanced/patches/music/layout/upgradebutton/fingerprints/PivotBarConstructorFingerprint.kt
Weirdly enough, this was the fingerprint used before the latest PR fix. So we are in fact returning to an old fingerprint...
=> fix(YouTube Music): Make `Hide 'Get Music Premium' label` and `Remove upgrade button` compatible with latest version

src/main/kotlin/app/revanced/patches/youtube/layout/buttons/navigation/NavigationButtonsPatch.kt, src/main/kotlin/app/revanced/patches/youtube/layout/buttons/navigation/fingerprints/CreatePivotBarFingerprint.kt, src/main/kotlin/app/revanced/patches/youtube/layout/buttons/navigation/fingerprints/HideNavigationButtonLabelsFingerprint.kt, src/main/resources/addresources/values/strings.xml
close https://github.com/ReVanced/revanced-patches/issues/3187
integrations https://github.com/ReVanced/revanced-integrations/pull/635
Credits to @inotia00 for fingerprint
=> feat(YouTube - Navigation buttons): Add option to hide navigation button labels

src/main/kotlin/app/revanced/patches/youtube/layout/hide/comments/CommentsPatch.kt, src/main/resources/addresources/values/strings.xml
https://github.com/ReVanced/revanced-integrations/pull/656
=> feat(YouTube - Comments): Add `Hide 'Create a Short' button` option

api/revanced-patches.api, src/main/kotlin/app/revanced/patches/instagram/patches/ad/HideAdsPatch.kt, src/main/kotlin/app/revanced/patches/instagram/patches/ad/fingerprints/AdInjectorFingerprint.kt
=> feat(Instagram): Add `Hide ads` patch

src/main/kotlin/app/revanced/patches/youtube/video/information/VideoInformationPatch.kt, src/main/kotlin/app/revanced/patches/youtube/video/information/fingerprints/MdxPlayerDirectorFingerprint.kt, src/main/kotlin/app/revanced/patches/youtube/video/information/fingerprints/MdxPlayerDirectorSetVideoStageFingerprint.kt, src/main/kotlin/app/revanced/patches/youtube/video/information/fingerprints/MdxSeekFingerprint.kt
Add patch code to support skipping segments while casted to a big screen device, by hooking the MDX director class to intercept object instances in order to be able to call the seekTo method, similar to how it's done in the 'regular' player class.
Fixes https://github.com/ReVanced/revanced-patches/issues/374.
Integrations PR: https://github.com/ReVanced/revanced-integrations/pull/655
=> fix(YouTube - SponsorBlock): Skip segments when casting

src/main/kotlin/app/revanced/patches/instagram/patches/ad/fingerprints/AdInjectorFingerprint.kt
Updated the fingerprint of the `Hide ads` patch for the `340.0.0.22.109` version
Should i lock this patch to a specific app version?
=> fix(Instagram - Hide ads):  Restore compatibility with latest version by fixing fingerprint

src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/SpoofClientPatch.kt, src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/fingerprints/GetTrackingUriFingerprint.kt, src/main/resources/addresources/values/strings.xml
RE: https://github.com/ReVanced/revanced-integrations/pull/669
=> fix(YouTube - Spoof client): Fix tracking history on brand accounts

api/revanced-patches.api, src/main/kotlin/app/revanced/patches/googlephotos/features/SpoofBuildInfoPatch.kt, src/main/kotlin/app/revanced/patches/googlephotos/features/SpoofFeaturesPatch.kt, src/main/kotlin/app/revanced/patches/googlephotos/features/fingerprints/InitializeFeaturesEnumFingerprint.kt, src/main/kotlin/app/revanced/patches/shared/misc/gms/BaseGmsCoreSupportPatch.kt
Enables the features listed here by default: https://github.com/ReVanced/revanced-patches/pull/3459/files#diff-c26b0f29d02c8f6c0b211d8982a0993591fc38ab0fe1f451f1e03f5eb0e50394R28-R35. All other features are disabled.
=> feat(Google Photos): Add `Spoof features` patch

src/main/kotlin/app/revanced/patches/swissid/integritycheck/RemoveGooglePlayIntegrityCheck.kt
Found this when surfing the ReVanced Website for issue to bother them (in a friendly way, of course. totally)
=> fix(SwissID): Rename `Remove Google Play Integrity Integrity check` to `Remove Google Play Integrity check`

api/revanced-patches.api, src/main/kotlin/app/revanced/patches/all/directory/ChangeDataDirectoryLocationPatch.kt
Added a patch to automate changing app files location from data/0 to android/data for root-less devices
=> feat: Add `Change data directory location` patch

src/main/kotlin/app/revanced/patches/soundcloud/ad/HideAdsPatch.kt, src/main/kotlin/app/revanced/patches/soundcloud/ad/fingerprints/InterceptFingerprint.kt
- InterceptFingerprint is now resolving in newer versions (#3619)
Minimum version: `2024.09.03-beta`
Unfortunately, this pull request currently only works with the latest beta versions and makes older versions stop working. Is there an option to add an old fingerprint to support older versions? If so, how would I do that?
=> fix(Soundcloud - Hide ads): Support latest version

src/main/kotlin/app/revanced/patches/shared/misc/checks/BaseCheckEnvironmentPatch.kt, stub/src/main/java/android/os/Build.java
Integrations: https://github.com/ReVanced/revanced-integrations/pull/693
=> fix(YouTube - Check environment): Only use fields available since Android 8

src/main/kotlin/app/revanced/patches/twitter/misc/links/OpenLinksWithAppChooserPatch.kt
the patch has a suggested version set, but the version value set here is incorrect, causing users of the ReVanced-manager to receive a warning that they are not using a suggested correct value should be "10.48.0.release.0"
<https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=twitter+10.48.0-release.&bundles%5B%5D=apkm_bundles&bundles%5B%5D=apk_files>
(if it is inappropriate to change the values ​​in this patch itself and it should be handled somewhere else, pls comment)
=> fix(Twitter - Open links with app chooser): Fix incorrect version in compatibility list

src/main/kotlin/app/revanced/patches/soundcloud/ad/fingerprints/InterceptFingerprint.kt, src/main/kotlin/app/revanced/patches/soundcloud/ad/fingerprints/UserConsumerPlanConstructorFingerprint.kt, src/main/kotlin/app/revanced/patches/soundcloud/analytics/fingerprints/CreateTrackingApiFingerprint.kt, src/main/kotlin/app/revanced/patches/soundcloud/offlinesync/fingerprints/DownloadOperationsHeaderVerificationFingerprint.kt, src/main/kotlin/app/revanced/patches/soundcloud/offlinesync/fingerprints/DownloadOperationsURLBuilderFingerprint.kt, src/main/kotlin/app/revanced/patches/soundcloud/shared/fingerprints/FeatureConstructorFingerprint.kt
- Fingerprints are now resolved in the latest version ( #3696 )
TODO: 
Tested versions: `2024.09.12`, `2024.09.16`, `2024.09.20`
=> fix(Soundcloud): Support version `2024.09.20`

src/main/kotlin/app/revanced/patches/youtube/layout/hide/shorts/HideShortsComponentsResourcePatch.kt, src/main/resources/addresources/values/strings.xml
RE: https://github.com/ReVanced/revanced-integrations/pull/708
=> feat(YouTube - Hide Shorts components): Add option to hide like fountain

src/main/kotlin/app/revanced/patches/backdrops/misc/pro/ProUnlockPatch.kt
By using [APKeditor](https://github.com/REAndroid/APKEditor?tab=readme-ov-file#3--merge) or [AntiSplit M](https://github.com/AbdurazaaqMohammed/AntiSplit-M) you can merge the bundle apk & patch all latest versions of Backdrops.
=> feat(Backdrops): Remove version constraint

src/main/kotlin/app/revanced/patches/youtube/layout/hide/shorts/HideShortsComponentsResourcePatch.kt, src/main/resources/addresources/values/strings.xml
Closes https://github.com/ReVanced/revanced-patches/issues/3751
[Integration changes](https://github.com/ReVanced/revanced-integrations/pull/714)
=> feat(YouTube - Hide Shorts components): Hide `Use template`, `Upcoming`, `Green screen` buttons

src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/SpoofVideoStreamsPatch.kt
Integrations: https://github.com/ReVanced/revanced-integrations/pull/716
=> fix(YouTube - Spoof video streams): Fix playback for Android VR by removing invalid body as well

src/main/kotlin/app/revanced/patches/twitter/interaction/downloads/fingerprints/BuildMediaOptionsSheetFingerprint.kt, src/main/kotlin/app/revanced/patches/twitter/interaction/downloads/fingerprints/ShowDownloadVideoUpsellBottomSheetFingerprint.kt
Some strings got removed, tested patching and it seems to work on 10.64.0-alpha, may need more testing
Should fix #3777
=> fix(Twitter - Unlock downloads):  Make it work with latest versions

api/revanced-patches.api, src/main/kotlin/app/revanced/patches/twitter/misc/links/ChangeLinkSharingDomainPatch.kt, src/main/kotlin/app/revanced/patches/twitter/misc/links/fingerprints/LinkBuilderFingerprint.kt, src/main/kotlin/app/revanced/patches/twitter/misc/links/fingerprints/LinkResourceGetterFingerprint.kt, src/main/kotlin/app/revanced/patches/twitter/misc/links/fingerprints/LinkSharingDomainFingerprint.kt
Revisit to the same patch I failed to finish before. This time integrations helped to simplify the code immensely!
Integration is in a separate pull request https://github.com/ReVanced/revanced-integrations/pull/715
Should resolve https://github.com/ReVanced/revanced-patches/issues/764
=> feat(Twitter): Add `Change link sharing domain` patch

src/main/kotlin/app/revanced/patches/twitter/misc/links/ChangeLinkSharingDomainPatch.kt, src/main/kotlin/app/revanced/patches/twitter/misc/links/ChangeLinkSharingDomainResourcePatch.kt, src/main/kotlin/app/revanced/patches/twitter/misc/links/fingerprints/LinkResourceGetterFingerprint.kt
New alpha version broke the patch, I switched to finding a resource id here so it should be more stable in the future.
=> fix(Twitter - Change link sharing domain): Support latest app version

src/main/kotlin/app/revanced/patches/youtube/layout/hide/general/HideLayoutComponentsPatch.kt, src/main/resources/addresources/values/strings.xml
With 19.24 and later, the video player can show under the video a shopping shelf with merchandise from the channel.
Enabling `hide horizontal shelves` will hide this, but this can be selectively hidden since this is the only shelf that can appear in the video player.
This PR adds a new hide ads setting to hide this specific type of shelf (enabled by default).
[Integration changes](https://github.com/ReVanced/revanced-integrations/pull/723)
=> feat(YouTube - Hide layout components): Hide player shopping shelf

extensions/shared/src/main/java/app/revanced/extension/youtube/patches/announcements/AnnouncementsPatch.java, extensions/shared/src/main/java/app/revanced/extension/youtube/patches/announcements/requests/AnnouncementsRoutes.java
This PR updates the Announcements patch to use API v4. With v4 now, the ID can be requested only. Announcements also now have an archived_at field. If the announcement is archived, even if it's the latest and has not been read, it will not be shown. This is useful for new users when the announcement is no longer relevant.
=> chore(YouTube - Announcements): Use API v4 to get announcements

patches/src/main/kotlin/app/revanced/patches/myexpenses/misc/pro/UnlockProPatch.kt
Restores a version constrain that was present but got lost in the patcher 5.0 migration
https://github.com/ReVanced/revanced-patches/commit/f68c87b0edc88e80ef2f3110f75be86236dffdb7
=> fix(My Expenses - Unlock pro): Constrain compatible version to working version

extensions/shared/src/main/java/app/revanced/extension/youtube/patches/VideoInformation.java, extensions/shared/src/main/java/app/revanced/extension/youtube/patches/playback/speed/RememberPlaybackSpeedPatch.java, patches/api/patches.api, patches/src/main/kotlin/app/revanced/patches/youtube/video/information/VideoInformationPatch.kt
Fixes tap and hold for 2x speed not working when using a default playback speed.
If using custom playback speeds and the current speed is higher than 2.0x, then the hold for 2x effectively does nothing.  It's caused by the logic in YouTube assuming the playback speed cannot be above it's unpatched max of 2.0x
=> fix(YouTube - Playback speed): Allow long press 2x speed when using custom playback speeds

extensions/shared/src/main/java/app/revanced/extension/youtube/patches/spoof/ClientType.java, extensions/shared/src/main/java/app/revanced/extension/youtube/patches/spoof/requests/PlayerRoutes.java, extensions/shared/src/main/java/app/revanced/extension/youtube/patches/spoof/requests/StreamingDataRequest.java, patches/src/main/resources/addresources/values/arrays.xml, patches/src/main/resources/addresources/values/strings.xml
YouTube now has restricted the auth token to their respective client. This mean's the Android token can not be used for iOS or VR requests anymore (More info https://github.com/yt-dlp/yt-dlp/issues/11640#issuecomment-2501049515).
Private or kids' videos can not be played without logging in.
The only solution here is to ask the user to log in, or somehow handle the login to other clients when the user logs into GmsCore.
Currently, VR seems to work with the Android auth token. This means, that private videos will work. What won't work is private kids videos, because VR is the only authorized client currently,  and that one can't play kids videos.
=> fix(YouTube - Spoof video streams): Log out the iOS client to allow kids videos playback

patches/src/main/kotlin/app/revanced/patches/twitch/ad/audio/AudioAdsPatch.kt, patches/src/main/kotlin/app/revanced/patches/twitch/ad/embedded/EmbeddedAdsPatch.kt, patches/src/main/kotlin/app/revanced/patches/twitch/ad/embedded/Fingerprints.kt, patches/src/main/kotlin/app/revanced/patches/twitch/ad/video/VideoAdsPatch.kt, patches/src/main/kotlin/app/revanced/patches/twitch/chat/antidelete/ShowDeletedMessagesPatch.kt, patches/src/main/kotlin/app/revanced/patches/twitch/chat/autoclaim/AutoClaimChannelPointsPatch.kt, patches/src/main/kotlin/app/revanced/patches/twitch/misc/settings/SettingsPatch.kt
This fixes patching errors, however late versions of Twitch are only bundles and the last ones that are APK fail to compile due to resources being decoded incorrectly. Neither of which is matter for the patches though.
=> feat(Twitch): Make patches compatible with latest versions

.github/workflows/pull_strings.yml
Turns off pushing of strings during pull action.
Without this, during a pull it's also pushing:
https://github.com/ReVanced/revanced-patches/actions/runs/12392938624/job/34593159582
```
STARTING CROWDIN ACTION
(https://github.com/ReVanced/revanced-patches/actions/runs/12392938624/job/34593159582#step:5:31)
UPLOAD SOURCES
(https://github.com/ReVanced/revanced-patches/actions/runs/12392938624/job/34593159582#step:5:32)
✔️  Fetching project info
(https://github.com/ReVanced/revanced-patches/actions/runs/12392938624/job/34593159582#step:5:33)
✔️  File 'strings.xml'
DOWNLOAD TRANSLATIONS
(https://github.com/ReVanced/revanced-patches/actions/runs/12392938624/job/34593159582#step:5:42)
✔️  Fetching project info
(https://github.com/ReVanced/revanced-patches/actions/runs/12392938624/job/34593159582 …
```
=> ci: Don't upload strings to Crowdin when pulling

patches/src/main/kotlin/app/revanced/patches/photomath/detection/deviceid/SpoofDeviceIdPatch.kt, patches/src/main/kotlin/app/revanced/patches/photomath/detection/signature/Fingerprints.kt, patches/src/main/kotlin/app/revanced/patches/photomath/misc/annoyances/HideUpdatePopupPatch.kt, patches/src/main/kotlin/app/revanced/patches/photomath/misc/unlock/plus/UnlockPlusPatch.kt
Tested on Photomath 8.43.0
I removed the version constraints since all patches succeed, but I'm not sure about `Hide update popup` since it was constrained to an older version than the rest of the patches. I can't test it because there wouldn't be an update to trigger such a popup.
=> feat(Photomath): Support latest version

extensions/twitter/src/main/java/app/revanced/twitter/patches/hook/twifucker/TwiFucker.kt
twitter has started (a long ago) to use `who-to-subscribe-` prefix instead of `who-to-follow-`
this adds the new prefix, so it is properly blocked again
[!fixes ](https://github.com/ReVanced/revanced-patches/issues/521)
=> fix(Twitter - Hide recommended users): add new timeline entryId prefix

extensions/spotify/src/main/java/app/revanced/extension/spotify/misc/UnlockPremiumPatch.java
For some people, including myself, Spotify Connect is restricted behind Premium subscription. This PR simply removes this restriction. This would also close https://github.com/ReVanced/revanced-patches/issues/4675 (although is already closed since no other people reported it).
=> fix(Spotify - Unlock Spotify Premium): Remove premium restriction on Spotify Connect 

extensions/youtube/src/main/java/app/revanced/extension/youtube/settings/Settings.java, extensions/youtube/src/main/java/app/revanced/extension/youtube/swipecontrols/SwipeControlsConfigurationProvider.kt, extensions/youtube/src/main/java/app/revanced/extension/youtube/swipecontrols/SwipeControlsHostActivity.kt, extensions/youtube/src/main/java/app/revanced/extension/youtube/swipecontrols/controller/VolumeKeysController.kt, extensions/youtube/src/main/java/app/revanced/extension/youtube/swipecontrols/controller/gesture/core/BaseGestureController.kt, extensions/youtube/src/main/java/app/revanced/extension/youtube/swipecontrols/controller/gesture/core/VolumeAndBrightnessScroller.kt, extensions/youtube/src/main/java/app/revanced/extension/youtube/swipecontrols/views/SwipeControlsOverlayLayout.kt, patches/src/main/kotlin/app/revanced/patches/youtube/interaction/swipecontrols/SwipeControlsPatch.kt, patches/src/main/resources/addresources/values/strings.xml
It's super annoying to scroll through 160 volume levels, so I've added an option to customize how much volume a single swipe changes.
May fix #1646, #3094, #1108
=> feat(YouTube - Swipe controls): Add option to change volume swipe sensitivity

patches/api/patches.api, patches/src/main/kotlin/app/revanced/patches/spotify/misc/fix/Fingerprints.kt, patches/src/main/kotlin/app/revanced/patches/spotify/misc/fix/SpoofPackageInfoPatch.kt, patches/src/main/kotlin/app/revanced/patches/spotify/misc/fix/SpoofSignaturePatch.kt
Spoofing the installer's name may or may not work. Currently testing. So far pretty much everyone reports it's working.
=> fix(Spotify): Fix login by replacing `Spoof signature` patch with new `Spoof package info` patch

patches/src/main/kotlin/app/revanced/patches/twitter/misc/dynamiccolor/DynamicColorPatch.kt, patches/src/main/kotlin/app/revanced/patches/twitter/misc/hook/HookPatch.kt, patches/src/main/kotlin/app/revanced/patches/twitter/misc/links/ChangeLinkSharingDomainPatch.kt, patches/src/main/kotlin/app/revanced/patches/twitter/misc/links/SanitizeSharingLinksPatch.kt
Devs of X/Twitter removed pairip in 10.85.
10.87 or up has issue https://github.com/ReVanced/revanced-patches/issues/4719.
So, 10.86 is last known good version.
=> feat(X / Twitter): Support version `10.86.0-release.0`

extensions/spotify/src/main/java/app/revanced/extension/spotify/layout/hide/createbutton/HideCreateButtonPatch.java, extensions/spotify/src/main/java/app/revanced/extension/spotify/misc/UnlockPremiumPatch.java
Just now realized this issue. I saw some users claiming all navigation bar items were getting hidden, and this might be why.
=> fix(Spotify): Prevent hiding all navigation bar buttons

patches/src/main/kotlin/app/revanced/patches/reddit/customclients/baconreader/api/SpoofClientPatch.kt
Exact same change as #5392 but for Bacon reader discussed in #5387.
=> fix(Bacon Reader - Spoof client): Use www instead of ssl API to fix auth related issues 

extensions/youtube/src/main/java/app/revanced/extension/youtube/patches/DisableChapterSkipDoubleTapPatch.java, extensions/youtube/src/main/java/app/revanced/extension/youtube/settings/Settings.java, patches/api/patches.api, patches/src/main/kotlin/app/revanced/patches/youtube/interaction/doubletap/DisableChapterSkipDoubleTapPatch.kt, patches/src/main/kotlin/app/revanced/patches/youtube/interaction/doubletap/Fingerprints.kt, patches/src/main/resources/addresources/values/strings.xml
Implements my suggested solution to #5356 . Very bare-bones (no in-app config option, only one verified supported version) because I'm not particularly experienced with ReVanced patches and because it's late at night when I'm writing this and I want to go to sleep.
The patch seems to work, in that I couldn't reproduce the bug on an emulator, however it would've been harder to reproduce on an emulator anyway, so I might've just not tested it enough. I did confirm that jumping to a chapter explicitly through the menu still works, though. The patch is off by default because I suppose some people might want to keep the original skip to chapter gesture.
Any help, improvements or feedback would be appreciated. @oSumAtrIX , since you were the one who reviewed my issue, you might want to review …
=> feat(YouTube): Disable two-finger tap gesture for skipping chapters
