src/main/kotlin/app/revanced/patches/youtube/layout/fullscreenpanels/annotations/FullscreenPanelsCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/layout/fullscreenpanels/patch/FullscreenPanelsRemoverPatch.kt
Hides 'engagement panels' (comments, playlist) when in fullscreen mode
=> feat: `disable-fullscreen-panels` patch

src/main/kotlin/app/revanced/patches/youtube/ad/general/annotation/GeneralAdsCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/ad/video/annotations/VideoAdsCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/annotation/SeekbarTappingCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/layout/amoled/annotations/AmoledCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/layout/createbutton/annotations/CreateButtonCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/layout/minimizedplayback/annotations/MinimizedPlaybackCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/layout/oldqualitylayout/annotations/OldQualityLayoutCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/layout/reels/annotations/HideReelsCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/annotations/ShortsButtonCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/misc/integrations/annotations/IntegrationsCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/misc/manifest/annotations/FixLocaleConfigErrorCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/misc/microg/annotations/MicroGPatchCompatibility.kt
Tested the patches on 17.23.35 and they all work fine, so this YouTube version should be added.
=> feat: bump compatibility for patches for Youtube to v17.23.35

src/main/kotlin/app/revanced/patches/youtube/misc/enabledebugging/annotations/EnableDebuggingCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/misc/enabledebugging/patch/EnableDebuggingPatch.kt
small patch to set [android:debuggable](https://developer.android.com/guide/topics/manifest/application-element#debug) attribute in manifest. 
This can be useful when developing new patches because it enables the use of some Android studio tools, like
- package filter on logcat
- [Layout Inspector](https://developer.android.com/studio/debug/layout-inspector#layout-inspector)
- Debugging revanced-integrations code (breakpoints and all that good stuff)
- ...
=> feat: Enable-Debugging Patch

src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/annotations/ShortsButtonCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/fingerprints/PivotBarButtonsViewFingerprint.kt, src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/patch/ShortsButtonRemoverPatch.kt
This fixes an error when applying this patch on v17.28.34 (and most likely other future versions) while still working with versions mentioned on the compatibility class.
=> fix: make `hide-shorts-button` fingerprint more future-proof

src/main/kotlin/app/revanced/patches/music/ad/video/annotations/MusicVideoAdsCompatibility.kt, src/main/kotlin/app/revanced/patches/music/audio/codecs/annotations/CodecsUnlockCompatibility.kt, src/main/kotlin/app/revanced/patches/music/audio/exclusiveaudio/annotations/ExclusiveAudioCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/compactheader/annotations/CompactHeaderCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/minimizedplayback/annotations/MinimizedPlaybackCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/premium/annotations/HideGetPremiumCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/tastebuilder/annotations/RemoveTasteBuilderCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/upgradebutton/annotations/RemoveUpgradeButtonCompatibility.kt, src/main/kotlin/app/revanced/patches/music/premium/backgroundplay/annotations/BackgroundPlayCompatibility.kt
not sure if I should make an issue regarding this. but I made a root only build a couple days ago which works fine here 
I included the following patches on version 5.16.51:
INFO: minimized-playback-music succeeded 
INFO: tasteBuilder-remover succeeded 
INFO: hide-get-premium succeeded 
INFO: upgrade-button-remover succeeded 
INFO: background-play succeeded 
INFO: music-video-ads succeeded 
INFO: codecs-unlock succeeded 
INFO: exclusive-audio-playback succeeded 
everything seems to work fine here and I haven't heard any complaints from others.
I used the following versions of the revanced things:
[revanced/revanced-patches: v2.21.3](https://github.com/revanced/revanced-patches/releases/tag/v2.21.3)
[revanced/revanced-integrations: …
=> fix: bump youtube music version to 5.16.51

src/main/kotlin/app/revanced/patches/youtube/misc/videoid/patch/VideoIdPatch.kt
This PR gets rid of the offset when injecting calls. This means that calls will be inserted in reverse order. 
Patches do not depend on each other when they use the VideoId patch as a dependency, hence the order of these calls can be removed. This should be reviewed by @j4k0xb.
=> refactor: do not account for order in `VideoIdPatch.injectCall`

README.md, src/main/kotlin/app/revanced/patches/warnwetter/misc/promocode/annotations/PromoCodeUnlockCompatibility.kt, src/main/kotlin/app/revanced/patches/warnwetter/misc/promocode/fingerprints/PromoCodeUnlockFingerprint.kt, src/main/kotlin/app/revanced/patches/warnwetter/misc/promocode/patch/PromoCodeUnlockPatch.kt
This adds a patch for the WarnWetter app, which enables the unlocking of all features via any string in promo code activation field.
I tested it and for it worked for me.
The patch and so on is a bit ugly since this is my first kotlin code and revanced patch. Thanks again to oSumAtrIX and canny.
Screenshot from App..
=> feat: promo-code-unlock patch

src/main/kotlin/app/revanced/patches/warnwetter/misc/firebasegetcert/annotations/FirebaseGetCertPatchCompatibility.kt, src/main/kotlin/app/revanced/patches/warnwetter/misc/firebasegetcert/fingerprints/GetCertMessagingFingerprint.kt, src/main/kotlin/app/revanced/patches/warnwetter/misc/firebasegetcert/fingerprints/GetCertRegistrationFingerprint.kt, src/main/kotlin/app/revanced/patches/warnwetter/misc/firebasegetcert/patch/FirebaseGetCertPatch.kt, src/main/kotlin/app/revanced/patches/warnwetter/misc/promocode/patch/PromoCodeUnlockPatch.kt
Closes #314, spoofs the `X-Android-Cert` header in order to allow push notifications to be sent to the patched app.
=> fix: WarnWetter failing to register push registration

.releaserc, build.gradle.kts
This should work as a cross-platform solution both for desktop and mobile!
It basically inserts the dex file inside the jar file so that it can be used on desktop with the JarPatchBundle (as it is now) and for mobile with the DexPatchBundle. Using only the dex file in mobile was not possible due to missing resources on the dex file.
Merging both is the solution :)
Semantic release file was also updated as after merging this, the jar asset is enough for both platforms.
=> feat: bundle dex file into jar file

src/main/kotlin/app/revanced/patches/youtube/layout/branding/icon/patch/CustomBrandingPatch.kt
InputStream.readAllBytes was only introduced [on Android in API 33](https://developer.android.com/reference/java/io/InputStream#readAllBytes()) so we need an implementation for a wider adoption :)
=> fix: make `custom-branding` cross-platform

src/main/kotlin/app/revanced/patches/youtube/misc/microg/patch/bytecode/MicroGBytecodePatch.kt
Fixed syntax issue in order to make use of regex patterns.
I made a GUI [ReVanced Patcher](https://github.com/iklevente/ReVanced-Sharper) that can dynamically add apps and patches so I need to make use of the revanced-patches readme.md document.
It's a great way to group apps together by patches and version compatibility so it would be nice to see to follow the generated syntaxes everywhere.
=> Fixed syntax issue

src/main/resources/sponsorblock/host/values/strings.xml
- fix definition of `music_offtopic` to be accurate
- fix definition of interaction reminder to not be specific to middle of content
- update definition of preview to remove "clips" clause
=> fix(sponsorblock): update strings to reflect guidelines

src/main/resources/sponsorblock/host/values/strings.xml
The current wording of the "privateID/ userID" is causing revanced users to constantly leak their privateIDs in the SponsorBlock discord.
The point of this wording to change is to explicitly reinforce that this is not the public component, this is the private component.
=> fix(sponsorblock): fix wording of "privateID"

src/main/kotlin/app/revanced/patches/ticktick/misc/themeunlock/annotations/UnlockThemesCompatibility.kt, src/main/kotlin/app/revanced/patches/ticktick/misc/themeunlock/fingerprints/CheckLockedThemesFingerprint.kt, src/main/kotlin/app/revanced/patches/ticktick/misc/themeunlock/fingerprints/ProThemesFingerprint.kt, src/main/kotlin/app/revanced/patches/ticktick/misc/themeunlock/fingerprints/SetThemeFingerprint.kt, src/main/kotlin/app/revanced/patches/ticktick/misc/themeunlock/patch/UnlockThemePatch.kt
This removes the requirements from the themes in [TickTick](https://play.google.com/store/apps/details?id=com.ticktick.task).
Themes can either be locked to require a certain amount of achievements, which is removed by the [CheckLockedThemesFingerprint](src/main/kotlin/app/revanced/patches/ticktick/misc/themeunlock/fingerprints/CheckLockedThemesFingerprint.kt), or require the user to have a premium account (fixed by the [ProThemesFingerprint](src/main/kotlin/app/revanced/patches/ticktick/misc/themeunlock/fingerprints/ProThemesFingerprint.kt)).
=> feat(ticktick): unlock all themes

src/main/kotlin/app/revanced/patches/twitch/debug/annotations/DebugModeCompatibility.kt, src/main/kotlin/app/revanced/patches/twitch/debug/fingerprints/IsDebugConfigEnabledFingerprint.kt, src/main/kotlin/app/revanced/patches/twitch/debug/fingerprints/IsOmVerificationEnabledFingerprint.kt, src/main/kotlin/app/revanced/patches/twitch/debug/fingerprints/ShouldShowDebugOptionsFingerprint.kt, src/main/kotlin/app/revanced/patches/twitch/debug/patch/DebugModePatch.kt
This patch unlocks a hidden debug mode in the Twitch app. The patch is excluded by default (just like the `enable-debugging` patch for YouTube).
It enables UI testing (inject fake comments, for example), web API testing (verbose GraphQL logging), a crash handler with an on-screen stack-trace display, and some more stuff.
This debug mode is very helpful while creating and debugging patches for Twitch.
=> feat(twitch/debug-mode): Enables Twitch's internal debugging mode

src/main/kotlin/app/revanced/patches/twitch/ad/audio/annotations/AudioAdsCompatibility.kt, src/main/kotlin/app/revanced/patches/twitch/ad/audio/fingerprints/AudioAdsPresenterPlayFingerprint.kt, src/main/kotlin/app/revanced/patches/twitch/ad/audio/patch/AudioAdsPatch.kt
This patch blocks [audio ads](https://help.twitch.tv/s/article/audio-ads?language=en_US) in the Twitch app (= stream is visible, but an ad takes over the audio).
I didn't even know these ads existed until I went through the decompilation, but luckily, Twitch's debug mode had the option to force show them in every stream so that I could test my blocking method properly.
=> feat(twitch/block-audio-ads): Blocks audio ads in streams and VODs

src/main/kotlin/app/revanced/patches/twitch/ad/video/annotations/VideoAdsCompatibility.kt, src/main/kotlin/app/revanced/patches/twitch/ad/video/fingerprints/AdsManagerFingerprint.kt, src/main/kotlin/app/revanced/patches/twitch/ad/video/fingerprints/CheckAdEligibilityLambdaFingerprint.kt, src/main/kotlin/app/revanced/patches/twitch/ad/video/fingerprints/ContentConfigShowAdsFingerprint.kt, src/main/kotlin/app/revanced/patches/twitch/ad/video/patch/VideoAdsPatch.kt
This patch should (hopefully) block (most) video ads in the Twitch app.
So far, this patch works reliably for me; however, the Twitch app has a massive amount of ad-related code, so I don't want to guarantee a 100% ad block rate. 
The app also contains code to handle ads that are embedded directly into the video stream. I didn't encounter embedded ads anywhere, and I doubt they are currently used; however, this patch won't be able to handle them if they suddenly start popping up.
=> feat(twitch/block-video-ads): Blocks video ads in streams and VODs (experimental)

src/main/kotlin/app/revanced/patches/tiktok/misc/settings/patch/TikTokSettingsPatch.kt
https://discord.com/channels/952946952348270622/1044056142864711751
=> fix(tiktok/settings): tiktok's settings patch name make 'revanced manager' confuse with youtube settings patch name

src/main/kotlin/app/revanced/patches/anytracker/misc/premium/annotations/UnlockPremiumCompatibility.kt, src/main/kotlin/app/revanced/patches/anytracker/misc/premium/fingerprints/IsPurchasedFlowFingerprint.kt, src/main/kotlin/app/revanced/patches/anytracker/misc/premium/patch/UnlockPremiumPatch.kt
Adds back `unlock-premium` patch.
RE: https://github.com/revanced/revanced-patches/pull/1094
After patching, signing the apk is not possible anymore:
```
com.android.apksig.apk.ApkFormatException: Malformed ZIP entry: LICENSE_OFL
at com.android.apksig.ApkSigner.sign(ApkSigner.java:359)
at com.android.apksig.ApkSigner.sign(ApkSigner.java:204)
at app.revanced.utils.signing.Signer.signApk(Signer.kt:77)
at app.revanced.cli.signing.Signing.sign(Signing.kt:10)
at app.revanced.cli.command.MainCommand.run(MainCommand.kt:168)
at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
at picocli.CommandLine.access$1500(CommandLine.java:148)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
at …
```
=> feat(anytracker): `unlock-premium` patch

src/main/kotlin/app/revanced/patches/music/ad/video/annotations/MusicVideoAdsCompatibility.kt, src/main/kotlin/app/revanced/patches/music/audio/codecs/annotations/CodecsUnlockCompatibility.kt, src/main/kotlin/app/revanced/patches/music/audio/exclusiveaudio/annotations/ExclusiveAudioCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/compactheader/annotations/CompactHeaderCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/minimizedplayback/annotations/MinimizedPlaybackCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/premium/annotations/HideGetPremiumCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/tastebuilder/annotations/RemoveTasteBuilderCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/upgradebutton/annotations/RemoveUpgradeButtonCompatibility.kt, src/main/kotlin/app/revanced/patches/music/misc/microg/annotations/MusicMicroGPatchCompatibility.kt, src/main/kotlin/app/revanced/patches/music/premium/backgroundplay/annotations/BackgroundPlayCompatibility.kt
Updates the compatibility of the YouTube Music patches to `5.24.31`. I checked, no fingerprint is failing, and all patches are still working.
=> feat(youtube-music): bump compatibility to 5.34.31

src/main/kotlin/app/revanced/patches/youtube/layout/theme/patch/ThemePatch.kt
This PR removed some unused colors names from patching list, because these don't change the color of any UI element from gray to black.
I added them because I thought they were all useful, but I was wrong. Only ```material_gray_850``` it's useful to change the color of context menus from gray to amoled.👍
=> refactor(youtube/theme): removed unused elements

src/main/kotlin/app/revanced/patches/youtube/misc/playercontrols/resource/patch/BottomControlsResourcePatch.kt
This caused an error when compiling resources with multiple bottom control button patches, but probably not noticed since only downloads patch was using this.
Current code returns: `/some_id`, when it should return `some_id`.
=> fix(youtube/BottomControls): wrong `nameSpaceLength`

src/main/kotlin/app/revanced/patches/youtube/misc/fix/verticalscroll/fingerprints/CanScrollVerticallyFingerprint.kt
The current fingerprint of ```swipe to reload``` fix patch is too short, and reach the wrong class method (the right one is ```n()```).
Patching output with the current fingerprint:
With this PR:
=> fix(youtube/vertical-scroll): wrong fingerprint

src/main/kotlin/app/revanced/patches/music/ad/video/annotations/MusicVideoAdsCompatibility.kt, src/main/kotlin/app/revanced/patches/music/audio/codecs/annotations/CodecsUnlockCompatibility.kt, src/main/kotlin/app/revanced/patches/music/audio/codecs/fingerprints/CodecsLockFingerprint.kt, src/main/kotlin/app/revanced/patches/music/audio/exclusiveaudio/annotations/ExclusiveAudioCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/compactheader/annotations/CompactHeaderCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/minimizedplayback/annotations/MinimizedPlaybackCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/premium/annotations/HideGetPremiumCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/tastebuilder/annotations/RemoveTasteBuilderCompatibility.kt, src/main/kotlin/app/revanced/patches/music/layout/upgradebutton/annotations/RemoveUpgradeButtonCompatibility.kt, src/main/kotlin/app/revanced/patches/music/misc/microg/annotations/MusicMicroGPatchCompatibility.kt, src/main/kotlin/app/revanced/patches/music/premium/backgroundplay/annotations/BackgroundPlayCompatibility.kt
Updates the compatibility of the YouTube Music patches to support `5.28.53`. All patches still work.
The `CodecsLockFingerprint` failed, so I changed `@FuzzyPatternScanMethod(2)` to `@FuzzyPatternScanMethod(3)`, which fixed it.
=> feat(YouTube-Music/compatibility): update to 5.38.53

src/main/kotlin/app/revanced/patches/youtube/layout/returnyoutubedislike/patch/ReturnYouTubeDislikePatch.kt, src/main/resources/returnyoutubedislike/host/values/strings.xml
RE: https://github.com/revanced/revanced-integrations/pull/284
Added an option for a slightly more narrow like button layout, that removes the left separator and tightens the space between the like/dislike by a few more pixels.
Mostly intended for users of devices with strange system fonts (such as [Xiaomi](https://github.com/revanced/revanced-integrations/issues/276)), or any other device where the left separator does not style well.
=> feat(YouTube): ReturnYouTubeDislike compact like button layout

.github/workflows/release.yml
This PR fixes the issue with CI failing until #1456 supersedes this.
=> ci: downgrade semantic release and plugins to v19

src/main/kotlin/app/revanced/patches/reddit/ad/general/annotations/GeneralAdsCompatibility.kt
The remove ads patch no longer fully works with the latest versions of Reddit.
Changed the patch so it requires the last version of Reddit that works correctly.
=> fix(Reddit): remove ads patch - specify last version that works correctly

src/main/kotlin/app/revanced/patches/idaustria/detection/root/fingerprints/RootDetectionFingerprint.kt, src/main/kotlin/app/revanced/patches/idaustria/detection/root/patch/RootDetectionPatch.kt, src/main/kotlin/app/revanced/patches/idaustria/detection/shared/annotations/DetectionCompatibility.kt, src/main/kotlin/app/revanced/patches/idaustria/detection/signature/fingerprints/SpoofSignatureFingerprint.kt, src/main/kotlin/app/revanced/patches/idaustria/detection/signature/patch/SpoofSignaturePatch.kt
Removes the root and bootloader open check from [ID Austria](https://play.google.com/store/apps/details?id=at.gv.oe.app&hl=de_AT&gl=US). It also spoofs the correct signature since the app checks the signature of the installed package.
=> feat(id-austria): Add root patch and signature spoof patch

src/main/kotlin/app/revanced/patches/twitter/layout/hideviews/annotations/HideViewsCompatibility.kt
hide-view-stats fails to patch with the recent twitter releases.   9.69.1-release.0 is the latest version that patches without errors, and works correctly.
=> fix(Twitter) specify Twitter version for hide-view-stats

src/main/kotlin/app/revanced/patches/finanzonline/detection/bootloader/fingerprints/BootStateFingerprint.kt, src/main/kotlin/app/revanced/patches/finanzonline/detection/bootloader/fingerprints/BootloaderDetectionFingerprint.kt, src/main/kotlin/app/revanced/patches/finanzonline/detection/bootloader/patch/BootloaderDetectionPatch.kt, src/main/kotlin/app/revanced/patches/finanzonline/detection/root/fingerprints/RootDetectionFingerprint.kt, src/main/kotlin/app/revanced/patches/finanzonline/detection/root/patch/RootDetectionPatch.kt, src/main/kotlin/app/revanced/patches/finanzonline/detection/shared/annotations/DetectionCompatibility.kt
Removes the root and bootloader check from [FinanzOnline [+]](https://play.google.com/store/apps/details?id=at.gv.bmf.bmf2go)
=> feat(finanzonline): Add root and bootloader detection removal patch

src/main/kotlin/app/revanced/patches/youtube/interaction/copyvideourl/resource/patch/CopyVideoUrlResourcePatch.kt, src/main/kotlin/app/revanced/patches/youtube/interaction/downloads/resource/patch/DownloadsResourcePatch.kt, src/main/kotlin/app/revanced/patches/youtube/interaction/swipecontrols/patch/resource/SwipeControlsResourcePatch.kt
fix for error message when switching on/off download video or copy video url.  The error occurred because the preference sub screen used the same key as an existing settings enum.
```
revanced: ReVancedSettingsFragment: Setting COPY_VIDEO_URL_BUTTON_SHOWN was changed. Preference revanced_copy_video_url: Copy video URL settings Settings related to copy URL buttons in video player
revanced: ReVancedSettingsFragment: Setting cannot be handled: class android.preference.PreferenceScreen Copy video URL settings Settings related to copy URL buttons in video player
```
the fix is to use a unique key for the setting enum.
integration changes: https://github.com/revanced/revanced-integrations/pull/307
=> fix(YouTube) error when switching on/off interaction setting

src/main/kotlin/app/revanced/patches/netguard/broadcasts/removerestriction/resource/annotations/RemoveBroadcastsRestrictionCompatibility.kt, src/main/kotlin/app/revanced/patches/netguard/broadcasts/removerestriction/resource/patch/RemoveBroadcastsRestrictionPatch.kt
Makes it possible to start/stop [NetGuard](https://github.com/M66B/NetGuard) via automation apps. Example for ADB to start NetGuard:
```
adb shell am broadcast --user 0 -a eu.faircode.netguard.ON eu.faircode.netguard
```
=> feat(netguard): remove-broadcasts-restriction

src/main/kotlin/app/revanced/patches/tiktok/interaction/seekbar/patch/ShowSeekbarPatch.kt
fix: https://discord.com/channels/952946952348270622/1068957976599212092
=> fix(tiktok/show-seekbar): fix crash because of npe.

src/main/kotlin/app/revanced/patches/twitter/ad/timeline/annotations/TimelineAdsCompatibility.kt, src/main/kotlin/app/revanced/patches/twitter/layout/hideviews/annotations/HideViewsCompatibility.kt, src/main/kotlin/app/revanced/patches/twitter/layout/hideviews/patch/HideViewsResourcePatch.kt
fixes https://github.com/revanced/revanced-patches/issues/352
changed:
- `timeline-ads` to require Twitter version 9.65.3
- `hide-views-stats` changed from default to optional (and added last version that works, `9.71.0`)
=> fix(twitter/timeline-ads): specify most recent app version that fully works

src/main/kotlin/app/revanced/patches/instagram/patches/ads/timeline/fingerprints/ShowAdFingerprint.kt
Tested for version 271.1.0.21.84
=> fix(instagram/hide-timeline-ads): fix compatibility with newer versions

.gitignore, gradle/wrapper/gradle-wrapper.properties
Update Gradle Wrapper to 8.0.1, and also ignore the gradle.properties file
> **Note**
> Users should execute `git update-index --skip-worktree gradle.properties` in order to skip previously tracked gradle.properties
=> Update Gradle Wrapper to 8.0.1

src/main/kotlin/app/revanced/patches/twitch/ad/audio/annotations/AudioAdsCompatibility.kt, src/main/kotlin/app/revanced/patches/twitch/ad/embedded/annotations/EmbeddedAdsCompatibility.kt, src/main/kotlin/app/revanced/patches/twitch/ad/video/annotations/VideoAdsCompatibility.kt, src/main/kotlin/app/revanced/patches/twitch/chat/antidelete/annotations/ShowDeletedMessagesCompatibility.kt, src/main/kotlin/app/revanced/patches/twitch/debug/annotations/DebugModeCompatibility.kt, src/main/kotlin/app/revanced/patches/twitch/misc/integrations/annotations/IntegrationsCompatibility.kt, src/main/kotlin/app/revanced/patches/twitch/misc/settings/annotations/SettingsCompatibility.kt
✨🤚 Feature - **Twitch** - Constraint compatibility to `14.6.1`
| APK name              | Version   | Status                 | Action                                                                               |
|-----------------------|-----------|------------------------|--------------------------------------------------------------------------------------|
| tv.twitch.android.app | 14.3.3    | ✅ Patching successful | ✋ Skipped |
| tv.twitch.android.app | 14.4.0    | ✅ Patching successful | ✋ Skipped |
| tv.twitch.android.app | 14.5.0    | ✅ Patching successful | ✋ Skipped  |
| tv.twitch.android.app | 14.5.2    | ✅ Patching successful | ✋ Skipped  |
| tv.twitch.android.app | 14.6.0    | ✅ Patching successful | ✋ Skipped  |
| tv.twitch.android.app | 14.6.1    | ✅ Patching successful | ✋ …
=> feat(twitch): constraint compatibility to `14.6.1`

src/main/kotlin/app/revanced/patches/youtube/layout/hide/floatingmicrophone/annotations/HideFloatingMicrophoneButtonCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/layout/hide/seekbar/annotations/HideSeekbarCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/layout/hide/watchinvr/annotations/WatchinVRCompatibility.kt, src/main/kotlin/app/revanced/patches/youtube/layout/searchbar/annotations/WideSearchbarCompatibility.kt
a followup to https://github.com/revanced/revanced-patches/pull/1704
4 patches were left out from the version bump:
`enable-wide-searchbar`, `hide-floating-microphone-button`, `hide-seekbar`, `hide-watch-in-vr`
These patches appear to work correctly with 18.05.40
Although I am unable to verify `hide-floating-microphone-button`, as I don't see any difference when using it on 18.03.36 or with 18.05.40 (I don't see any floating microphones anywhere in the app, regardless if the patch is turned on or off).
The other 3 patches work as expected with 18.05.40
=> feat(youtube): bump compatibility to 18.05.40 (additional patches)

src/main/kotlin/app/revanced/patches/ticktick/misc/themeunlock/patch/UnlockThemePatch.kt
🔧 Refactor - [TickTick](https://play.google.com/store/apps/details?id=com.ticktick.task) - Clarify `unlock-themes` description
refactor(TickTick): clarify the `unlock-themes` patch's description
```diff
- Unlocks all themes.
+ Unlocks all themes that are inaccessible until a certain level is reached.
```
When applying this patch, all themes that require you to reach specific levels are unlocked, but all themes that require you to have premium are not.
=> refactor(TickTick): clarify `unlock-themes` description

src/main/kotlin/app/revanced/patches/idaustria/detection/shared/annotations/DetectionCompatibility.kt
I have tested the new ID Austria version (`2.6.0`), and the patch still works, so this PR marks the version as compatible.
=> feat(id-austria): Add version 2.6.0

src/main/kotlin/app/revanced/patches/twitch/ad/embedded/patch/EmbeddedAdsPatch.kt
=> fix(twitch): minor spelling mistake in Description

src/main/kotlin/app/revanced/patches/idaustria/detection/shared/annotations/DetectionCompatibility.kt
Just tested the patch for version `2.6.1`, and it still works.
=> feat(id-austria): remove version constraint

src/main/kotlin/app/revanced/meta/PatchesFileGenerator.kt, src/main/kotlin/app/revanced/patches/all/misc/packagename/patch/ChangePackageNamePatch.kt
=> fix(change-package-name): make option `packageName` `null` by default

.github/ISSUE_TEMPLATE/bug-issue.yml, .github/ISSUE_TEMPLATE/patch-request.yml
- Add scope to `title` field. Alternatively, use `(patch)` instead of `(scope)`.
-  Fix typo in description of Patch Request
=> chore: remove scopes from issue templates

build.gradle.kts, src/main/kotlin/app/revanced/patches/youtube/misc/microg/fingerprints/GooglePlayUtilityFingerprint.kt, src/main/kotlin/app/revanced/patches/youtube/misc/microg/fingerprints/ServiceCheckFingerprint.kt, src/main/kotlin/app/revanced/util/microg/MicroGBytecodeHelper.kt
fixed signature resolving, required for https://github.com/revanced/revanced-patcher/pull/183
=> fix(youtube/vanced-microg-support): fix method fingerprint

src/main/kotlin/app/revanced/patches/songpal/badge/annotations/BadgeCompatibility.kt, src/main/kotlin/app/revanced/patches/songpal/badge/fingerprints/CreateTabsFingerprint.kt, src/main/kotlin/app/revanced/patches/songpal/badge/fingerprints/ShowNotificationFingerprint.kt, src/main/kotlin/app/revanced/patches/songpal/badge/patch/BadgeTabPatch.kt, src/main/kotlin/app/revanced/patches/songpal/badge/patch/RemoveNotificationBadgePatch.kt
Adds two patches to remove the "Badge" sub-tab in the "Activity" tab (see attached screenshot) as well as the red badge in the bottom navbar on the "Activity" tab since they may be perceived as annoying.
=> feat(songpal): Add patches for Sony's SongPal

build.gradle.kts, dummy/build.gradle.kts, dummy/src/main/java/android/os/Environment.java, settings.gradle.kts, src/main/kotlin/app/revanced/patches/syncforreddit/ads/annotations/DisableAdsCompatibility.kt, src/main/kotlin/app/revanced/patches/syncforreddit/ads/patch/DisableAdsPatch.kt, src/main/kotlin/app/revanced/patches/syncforreddit/api/fingerprints/GetAuthorizationStringFingerprint.kt, src/main/kotlin/app/revanced/patches/syncforreddit/api/fingerprints/GetBearerTokenFingerprint.kt, src/main/kotlin/app/revanced/patches/syncforreddit/api/patch/ChangeOAuthClientIdPatch.kt
This PR adds a patch for "Sync for Reddit" to change the client id to circumvent the upcoming restrictions on the API enforced by Reddit.
=> feat(syncforreddit): add `change-oauth-client-id` patch

src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/fingerprints/AbstractClientIdFingerprint.kt, src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/fingerprints/GetLoggedInBearerTokenFingerprint.kt, src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/fingerprints/GetLoggedOutBearerTokenFingerprint.kt, src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/fingerprints/GetRefreshTokenFingerprint.kt, src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/fingerprints/LoginActivityClientIdFingerprint.kt, src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api/patch/ChangeOAuthClientIdPatch.kt
Changes the patch to change the correct client id.
I somehow naively thought that `DeveloperKey` was the client id, but that's actually just for YouTube.
I tested the app better now to make sure it was actually using my client id.
Also fixes the patching error on the `@ChangeOAuthClientIdPatchAnnotation` by moving `@Patch` out of it.
=> fix(relayforreddit/change-oauth-client-id): change client id instead of developer key

src/main/kotlin/app/revanced/patches/reddit/customclients/redditisfun/api/patch/ChangeOAuthClientIdPatch.kt
Adds compatibility for "rif is fun golden platinum", RIF's paid ad-free version
=> fix(redditisfun/change-oauth-client-id): Add RIF Golden Platinum

src/main/kotlin/app/revanced/patches/tiktok/interaction/seekbar/fingerprints/ShouldShowSeekBarFingerprint.kt, src/main/kotlin/app/revanced/patches/tiktok/interaction/seekbar/patch/ShowSeekbarPatch.kt
Fix #2734 and fix a issue that patched tiktok can not show seekbar on sensitive video
=> fix(Tiktok/Show seekbar): bump compatibility

src/main/kotlin/app/revanced/patches/youtube/interaction/downloads/resource/patch/ExternalDownloadsResourcePatch.kt
Due to the fact that PowerTube has not been consistently maintained and occasionally experiences difficulties in downloading videos. Refer to:
https://github.com/razar-dev/PowerTube/issues/57
https://github.com/razar-dev/PowerTube/issues/56
https://github.com/razar-dev/PowerTube/issues/54
At present, Seal and YTDLnis utilize YT-dlp, resulting in improved output.
=> Remove PowerTube from download recommended app & add Seal

gradle/wrapper/gradle-wrapper.properties
- [Gradle Changelog](https://docs.gradle.org/8.3/release-notes.html)
This commit update the distributionUrl (or just basically version) in `gradle-wrapper.properties` to use Gradle 8.3
=> build: update Gradle to v8.3

build.gradle.kts
Fixes a deprecation after the update to v8.3 in #2843.
=> build: use supported API to get working directory

src/main/kotlin/app/revanced/patches/tumblr/annoyances/notifications/fingerprints/IsBlogNotifyEnabledFingerprint.kt, src/main/kotlin/app/revanced/patches/tumblr/annoyances/notifications/patch/DisableBlogNotificationReminderPatch.kt, src/main/kotlin/app/revanced/patches/tumblr/annoyances/popups/fingerprints/ShowGiftMessagePopupFingerprint.kt, src/main/kotlin/app/revanced/patches/tumblr/annoyances/popups/patch/DisableGiftMessagePopupPatch.kt
DisableGiftMessagePopupPatch:
Disables the "You can now give back to the people you love" popup when visiting a blog for the first time.
Adds a `return false` at the start of the `BlogNotifyCtaDialog.isEnabled` method
DisableBlogNotificationReminderPatch:
Disables the "Want to get a notification when this person posts?" popup when visiting a specific blog for the second time
Adds a `return` at the start of the `GiftMessagePopup.(showPopup)` method
=> feat(tumblr): Add anti-annoyance patches

src/main/kotlin/app/revanced/patches/tudortmund/lockscreen/fingerprints/BrightnessFingerprint.kt, src/main/kotlin/app/revanced/patches/tudortmund/lockscreen/patch/ShowOnLockscreenPatch.kt
Got annoyed by first having to unlock the screen to show the ticket to the bus driver ^^
[Integration changes](https://github.com/ReVanced/revanced-integrations/pull/472)
=> feat(TU Dortmund): Add `Show on lockscreen` patch

src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/ClientSpoofPatch.kt, src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/SpoofSignaturePatch.kt, src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/SpoofSignatureResourcePatch.kt, src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/SpoofSignatureVerificationPatch.kt, src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/SpoofSignatureVerificationResourcePatch.kt, src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/fingerprints/ScrubbedPreviewLayoutFingerprint.kt
This PR adds the option to disable or enable spoofing the client when playing videos from feeds. The reason is that playback should work for a decent amount (1 minute) where not spoofing is not too much of an issue compared to the video landing in history.  Those who do not care though and want to watch auto-playing videos over a minute can spoof them.
Depends on https://github.com/ReVanced/revanced-integrations/pull/478
=> fix(YouTube - Client spoof): Do not record feed videos to history by default

src/main/kotlin/app/revanced/patches/youtube/layout/branding/header/PremiumHeadingPatch.kt
Fixes an inverted logic caused by the [last commit](https://github.com/ReVanced/revanced-patches/pull/3029/commits/5f2f9676017f524d8315f095b18f1e74e85603f6) of #3029.
=> fix(YouTube - Premium heading): Correct inverted logic

src/main/kotlin/app/revanced/patches/serviceportalbund/detection/root/RootDetectionPatch.kt, src/main/kotlin/app/revanced/patches/serviceportalbund/detection/root/fingerprints/RootDetectionFingerprint.kt
Removes the root and bootloader open check from [SPB Serviceportal Bund](https://play.google.com/store/apps/details?id=at.gv.bka.serviceportal&hl=de_AT&gl=US). Based on patch for ID Austria.
=> feat(SPB Serviceportal Bund): Add `Remove root detection` patch

src/main/kotlin/app/revanced/patches/tumblr/annoyances/inappupdate/DisableInAppUpdatePatch.kt
Once per day, the Tumblr app checks for available app update using the Google play core AppUpdateManager api.  
If an update is available, a banner is shown above the bottom navbar, nudging the user to update.  
When the "Download" button in the banner is pressed, an in-app self-update is apparently supposed to be performed, but this doesn't actually work on my phone so it just causes the banner to disappear for the current day.  
Since updating revanced-patched apps is a bit of a pain, I am adding a patch to disable in-app updates by simply setting the inAppUpdate feature flag to false.
=> feat(Tumblr): Add `Disable in-app update` patch

src/main/kotlin/app/revanced/patches/youtube/ad/getpremium/HideGetPremiumPatch.kt
Closes https://github.com/ReVanced/revanced-patches/issues/3075
I edited the patch name to `Hide "Get Premium"` just like how the [Hide load more button patch was renamed](https://github.com/ReVanced/revanced-patches/commit/569c3cde9875b807c9116322ca324f69b5fa0218)
I tried checking and it didn't seem like I needed to change any integrations after changing the patch name.
=> feat(YouTube - Hide "Get YouTube Premium" advertisements): Name patch correctly

src/main/kotlin/app/revanced/patches/youtube/ad/getpremium/HideGetPremiumPatch.kt
Patch is already part of `Hide ads`, but during the recent refactoring it got a name added by mistake.
Changed "advertisement" to promo, to better indicates it's not advertisements Premium users will see, but instead a promotion to signup for YT Premium.
=> fix(YouTube - Hide get YouTube Premium advertisements): move patch to `Hide ads`

src/main/kotlin/app/revanced/patches/idaustria/detection/root/RootDetectionPatch.kt, src/main/kotlin/app/revanced/patches/idaustria/detection/signature/SpoofSignaturePatch.kt
The new version `3.0.0` is not supported yet. Not sure when I will have time to check it out, therefore I marked only `2.7.1` as compatible.
=> chore(id-austria): Set fixed version for ID Austria

src/main/kotlin/app/revanced/patches/youtube/layout/hide/player/flyoutmenupanel/HidePlayerFlyoutMenuPatch.kt
depends on:
- ReVanced/revanced-integrations/pull/502
=> fix(YouTube - Player flyout menu): Restore functionality

src/main/resources/sponsorblock/host/values/strings.xml
We are renaming the category to help clarify it
https://github.com/ajayyy/ExtensionTranslations/commit/7c71786bb3d27f9ff6d62d2575f17b4bfee89b34
=> fix(YouTube - SponsorBlock): Rename "Preview/Recap" category to "Preview/Recap/Hook"

src/main/kotlin/app/revanced/patches/spotify/layout/theme/CustomThemePatch.kt
This change replaces background theme in many more places. Examples given in screenshots.
=> fix(Spotify - Custom theme): Add more background surfaces coloring options

docs/3_fingerprinting.md
Just found this on my light reading.
=> docs: Fix broken link to `VideoAdsPatch`
