ReVanced/revanced-patches

src/main/kotlin/app/revanced/patches/Index.kt
src/main/kotlin/app/revanced/patches/music/audio/CodecsUnlockPatch.kt
src/main/kotlin/app/revanced/patches/music/audio/EnableAudioOnlyPatch.kt
src/main/kotlin/app/revanced/patches/music/layout/RemoveTasteBuilderPatch.kt
src/main/kotlin/app/revanced/patches/music/layout/RemoveUpgradeTabPatch.kt
src/main/kotlin/app/revanced/patches/music/premium/BackgroundPlayPatch.kt
src/main/kotlin/app/revanced/patches/youtube/ad/HomeAdsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/ad/HomePromoPatch.kt
src/main/kotlin/app/revanced/patches/youtube/ad/VideoAdsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/interaction/EnableSeekbarTappingPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/CreateButtonRemoverPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/HideReelsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/MinimizedPlaybackPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/OldQualityLayoutPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/ShortsButtonRemoverPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/FixLocaleConfigErrorPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/IntegrationsPatch.kt
src/test/kotlin/app/revanced/patches/SignatureChecker.kt

Addressing PR https://github.com/ReVancedTeam/revanced-patcher/pull/28

add: resource patcher

---

src/main/kotlin/app/revanced/patches/music/layout/upgradebutton/patch/RemoveUpgradeButtonPatch.kt

refactor: fix mispeling

---

src/main/kotlin/app/revanced/extensions/Extensions.kt

- Changes singular `prefix` vararg to `prefixes`.
- Changes `_prefix` in loop to `prefix`

refactor: more readable code

---

src/main/kotlin/app/revanced/patches/youtube/misc/microg/shared/Constants.kt

Reverts revanced/revanced-patches#21

revert: "Changed app name to ReVanced"

---

src/main/kotlin/app/revanced/patches/youtube/layout/createbutton/patch/CreateButtonRemoverPatch.kt

broken here https://github.com/revanced/revanced-patches/commit/a8f17948ac35be727cef97dcf574664c76d016c0#diff-5c4fb7bb00263bb43986cf3283d9cb47a139fbb2aa761863e026daf0287d96f8

fix: put back proper variable in create button patch

---

src/main/kotlin/app/revanced/patches/youtube/ad/general/annotation/GeneralAdsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/ad/video/annotations/VideoAdsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/annotation/SeekbarTappingCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/amoled/annotations/AmoledCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/createbutton/annotations/CreateButtonCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/fullscreenpanels/annotations/FullscreenPanelsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/minimizedplayback/annotations/MinimizedPlaybackCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/oldqualitylayout/annotations/OldQualityLayoutCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/reels/annotations/HideReelsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/annotations/ShortsButtonCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/integrations/annotations/IntegrationsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/manifest/annotations/FixLocaleConfigErrorCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/microg/annotations/MicroGPatchCompatibility.kt

Tested every patch in root and non-root version. Everything works as expected.

feat: add youtube version 17.24.35

---

src/main/kotlin/app/revanced/patches/youtube/ad/general/annotation/GeneralAdsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/ad/video/annotations/VideoAdsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/annotation/SeekbarTappingCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/amoled/annotations/AmoledCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/createbutton/annotations/CreateButtonCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/fullscreenpanels/annotations/FullscreenPanelsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/minimizedplayback/annotations/MinimizedPlaybackCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/oldqualitylayout/annotations/OldQualityLayoutCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/reels/annotations/HideReelsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/annotations/ShortsButtonCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/customplaybackspeed/annotations/CustomPlaybackSpeedCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/integrations/annotations/IntegrationsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/manifest/annotations/FixLocaleConfigErrorCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/microg/annotations/MicroGPatchCompatibility.kt

Tried and tested all patches. Working as expected.

feat: add youtube version 17.25.34

---

src/main/kotlin/app/revanced/patches/music/audio/exclusiveaudio/patch/ExclusiveAudioPatch.kt
src/main/kotlin/app/revanced/patches/music/layout/upgradebutton/patch/RemoveUpgradeButtonPatch.kt
src/main/kotlin/app/revanced/patches/youtube/ad/general/bytecode/patch/GeneralBytecodeAdsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/ad/video/patch/VideoAdsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/interaction/fenster/patch/FensterPatch.kt
src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/patch/EnableSeekbarTappingPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/autoplaybutton/patch/HideAutoplayButton.kt
src/main/kotlin/app/revanced/patches/youtube/layout/castbutton/patch/HideCastButtonPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/createbutton/patch/CreateButtonRemoverPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/fullscreenpanels/patch/FullscreenPanelsRemoverPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/minimizedplayback/patch/MinimizedPlaybackPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/oldqualitylayout/patch/OldQualityLayoutPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/reels/patch/HideReelsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/patch/ShortsButtonRemoverPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/watermark/patch/HideWatermarkPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/widesearchbar/patch/WideSearchbarPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/enabledebugging/patch/EnableDebuggingPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/patch/HDRBrightnessPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/manifest/patch/FixLocaleConfigErrorPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/mapping/patch/ResourceIdMappingProviderResourcePatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/microg/patch/bytecode/MicroGBytecodePatch.kt

Chose this format because I think its more user friendly than commit message style

fix: patch description consistency

---

src/main/kotlin/app/revanced/patches/music/premium/backgroundplay/patch/BackgroundPlayPatch.kt
src/main/kotlin/app/revanced/patches/youtube/ad/general/annotation/GeneralAdsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/ad/infocardsuggestions/annotations/HideInfocardSuggestionsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/ad/video/annotations/VideoAdsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/interaction/fenster/annotation/FensterCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/annotation/SeekbarTappingCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/amoled/annotations/AmoledCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/autoplaybutton/annotations/AutoplayButtonCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/autorepeat/annotations/AutoRepeatCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/branding/header/patch/PremiumHeadingPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/branding/icon/patch/CustomBrandingPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/createbutton/annotations/CreateButtonCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/fullscreenpanels/annotations/FullscreenPanelsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/minimizedplayback/annotations/MinimizedPlaybackCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/oldqualitylayout/annotations/OldQualityLayoutCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/reels/annotations/HideReelsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/annotations/ShortsButtonCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/watermark/annotations/HideWaterwarkCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/widesearchbar/annotations/WideSearchbarCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/customplaybackspeed/annotations/CustomPlaybackSpeedCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/annotations/HDRBrightnessCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/integrations/annotations/IntegrationsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/manifest/annotations/FixLocaleConfigErrorCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/microg/annotations/MicroGPatchCompatibility.kt

also some descriptions i missed last time

fix: update patches to `17.26.35`

---

src/main/kotlin/app/revanced/patches/music/ad/video/annotations/MusicVideoAdsCompatibility.kt
src/main/kotlin/app/revanced/patches/music/ad/video/fingerprints/ShowMusicVideoAdsConstructorFingerprint.kt
src/main/kotlin/app/revanced/patches/music/ad/video/fingerprints/ShowMusicVideoAdsFingerprint.kt
src/main/kotlin/app/revanced/patches/music/ad/video/patch/MusicVideoAdsPatch.kt

This is heavily based on the video-ads patch from YouTube.
Is anyone able to test this PR?
It appears to be working on my side as no ad is being triggered for some time but still...
Edit: been using for quite some time now and indeed no ad appears 👍

feat: `music-video-ads`

---

src/main/kotlin/app/revanced/patches/music/ad/video/patch/MusicVideoAdsPatch.kt
src/main/kotlin/app/revanced/patches/music/audio/codecs/patch/CodecsUnlockPatch.kt
src/main/kotlin/app/revanced/patches/music/audio/exclusiveaudio/patch/ExclusiveAudioPatch.kt
src/main/kotlin/app/revanced/patches/music/layout/tastebuilder/patch/RemoveTasteBuilderPatch.kt
src/main/kotlin/app/revanced/patches/music/layout/upgradebutton/patch/RemoveUpgradeButtonPatch.kt
src/main/kotlin/app/revanced/patches/youtube/ad/general/bytecode/patch/GeneralBytecodeAdsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/ad/video/patch/VideoAdsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/patch/EnableSeekbarTappingPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/autoplaybutton/patch/HideAutoplayButton.kt
src/main/kotlin/app/revanced/patches/youtube/layout/branding/header/patch/PremiumHeadingPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/branding/icon/patch/CustomBrandingPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/castbutton/patch/HideCastButtonPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/createbutton/patch/CreateButtonRemoverPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/fullscreenpanels/patch/FullscreenPanelsRemoverPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/oldqualitylayout/patch/OldQualityLayoutPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/reels/patch/HideReelsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/returnyoutubedislike/patch/ReturnYouTubeDislikePatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/patch/ShortsButtonRemoverPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/watermark/patch/HideWatermarkPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/customplaybackspeed/patch/CustomPlaybackSpeedPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/microg/patch/bytecode/MicroGBytecodePatch.kt

This commit updates patches description to make it more clear to new users

chore: Update patches description

---

src/main/kotlin/app/revanced/patches/music/layout/premium/annotations/HideGetPremiumCompatibility.kt
src/main/kotlin/app/revanced/patches/music/layout/premium/fingerprints/HideGetPremiumFingerprint.kt
src/main/kotlin/app/revanced/patches/music/layout/premium/fingerprints/HideGetPremiumParentFingerprint.kt
src/main/kotlin/app/revanced/patches/music/layout/premium/patch/HideGetPremiumPatch.kt

Before (original):
After partial patch (hidden bottom panel):
After successful patching:

feat: `hide-get-premium` patch

---

src/main/kotlin/app/revanced/patches/youtube/misc/settings/resource/patch/SettingsResourcePatch.kt

Has to be merged together with integrations PR:
- https://github.com/revanced/revanced-integrations/pull/110

fix: add missing permission to reboot app

---

src/main/kotlin/app/revanced/patches/warnwetter/misc/promocode/fingerprints/PromoCodeUnlockFingerprint.kt

fix: incorrect compatibilty attribute

---

src/main/kotlin/app/revanced/patches/youtube/ad/general/bytecode/patch/GeneralBytecodeAdsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/ad/infocardsuggestions/patch/HideInfocardSuggestionsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/patch/EnableSeekbarTappingPatch.kt
src/main/kotlin/app/revanced/patches/youtube/interaction/swipecontrols/patch/resource/SwipeControlsResourcePatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/autoplaybutton/patch/HideAutoplayButton.kt
src/main/kotlin/app/revanced/patches/youtube/layout/castbutton/patch/HideCastButtonPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/fullscreenpanels/patch/FullscreenPanelsRemoverPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/oldqualitylayout/patch/OldQualityLayoutPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/reels/patch/HideReelsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/patch/ShortsButtonRemoverPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/watermark/patch/HideWatermarkPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/patch/HDRBrightnessPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/minimizedplayback/patch/MinimizedPlaybackPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/videobuffer/patch/CustomVideoBufferPatch.kt

feat: finished populating settings

---

src/main/kotlin/app/revanced/patches/youtube/ad/general/bytecode/patch/GeneralBytecodeAdsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/ad/infocardsuggestions/patch/HideInfocardSuggestionsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/ad/video/patch/VideoAdsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/interaction/seekbar/patch/EnableSeekbarTappingPatch.kt
src/main/kotlin/app/revanced/patches/youtube/interaction/swipecontrols/patch/resource/SwipeControlsResourcePatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/autoplaybutton/patch/HideAutoplayButton.kt
src/main/kotlin/app/revanced/patches/youtube/layout/castbutton/patch/HideCastButtonPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/createbutton/patch/CreateButtonRemoverPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/fullscreenpanels/patch/FullscreenPanelsRemoverPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/oldqualitylayout/patch/OldQualityLayoutPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/reels/patch/HideReelsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/shorts/button/patch/ShortsButtonRemoverPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/watermark/patch/HideWatermarkPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/autorepeat/patch/AutoRepeatPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/patch/HDRBrightnessPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/minimizedplayback/patch/MinimizedPlaybackPatch.kt

chore: removed dots in some summaries for consistency

---

src/main/kotlin/app/revanced/patches/tiktok/ad/annotations/TiktokAdsCompatibility.kt
src/main/kotlin/app/revanced/patches/tiktok/ad/fingerprints/FeedItemListCloneFingerprint.kt
src/main/kotlin/app/revanced/patches/tiktok/ad/patch/TiktokAdsPatch.kt

This patch is untested because TikTok does not run on my emulator. If possible review this.

feat: `tiktok-ads` patch

---

src/main/kotlin/app/revanced/patches/music/misc/microg/fingerprints/CastContextFetchFingerprint.kt
src/main/kotlin/app/revanced/patches/music/misc/microg/fingerprints/CastDynamiteModuleFingerprint.kt
src/main/kotlin/app/revanced/patches/music/misc/microg/fingerprints/CastDynamiteModuleV2Fingerprint.kt
src/main/kotlin/app/revanced/patches/music/misc/microg/patch/bytecode/MusicMicroGBytecodePatch.kt

Temporary fix for overheating/battery issues in Youtube Music.

fix: disable cast in yt music

---

src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/annotations/DownloadsCompatibility.kt
src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/fingerprints/ACLCommonShareFingerprint.kt
src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/fingerprints/ACLCommonShareFingerprint2.kt
src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/fingerprints/ACLCommonShareFingerprint3.kt
src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/patch/DownloadsPatch.kt
src/main/kotlin/app/revanced/patches/tiktok/interaction/seekbar/annotations/SeekbarCompatibility.kt
src/main/kotlin/app/revanced/patches/tiktok/interaction/seekbar/fingerprints/AwemeGetVideoControlFingerprint.kt
src/main/kotlin/app/revanced/patches/tiktok/interaction/seekbar/patch/TiktokSeekbarPatch.kt

`tiktok-download` bypass downloads restriction on all video and remove watermark on downloaded videos.
`tiktok-seekbar` enable progresss bar for all video.

feat: [Tiktok patch] Add tiktok-download and tiktok-seekbar patch.

---

src/main/kotlin/app/revanced/patches/tiktok/ad/fingerprints/ConvertHelpFeedItemListFingerprint.kt
src/main/kotlin/app/revanced/patches/tiktok/ad/patch/TiktokAdsPatch.kt

@oSumAtrIX  I changed the PR like your suggestion. Please tell me if you have any further suggestions.

fix: tiktok-ads sometimes still show ads.

---

src/main/resources/downloads/drawable/revanced_yt_download_button.xml

fix: use proper path for download icon

---

src/main/resources/downloads/drawable/revanced_yt_download_button.xml

Had to make new PR due to #473 being marked as merged

re-align download button

---

src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/fingerprints/DownloadPathParentFingerprint.kt
src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/patch/DownloadsPatch.kt

Add a option to change videos' download path to `tiktok-download` patch.

feat(tiktok-download): Custom videos' download path.

---

src/main/resources/sponsorblock/host/values/strings.xml

Accompanying string changes for https://github.com/revanced/revanced-integrations/pull/143

feat(sponsorblock): add 400 error string

---

src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/patch/DownloadsPatch.kt

https://github.com/revanced/revanced-integrations/pull/152

refactor(tiktok): adapt `tiktok-download` with `tiktok-settings`.

---

src/main/kotlin/app/revanced/patches/spotify/layout/theme/annotations/ThemeCompatibility.kt
src/main/kotlin/app/revanced/patches/spotify/layout/theme/patch/ThemePatch.kt

feat: spotify-theme patch

---

src/main/kotlin/app/revanced/patches/youtube/layout/sponsorblock/bytecode/patch/SponsorBlockBytecodePatch.kt

This PR fixes the issue since that make youtube crash when play a video.

fix: youtube crash when play a video.

---

src/main/kotlin/app/revanced/patches/youtube/layout/personalinformation/annotations/HideEmailAddressCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/personalinformation/fingerprints/AccountSwitcherAccessibilityLabelFingerprint.kt
src/main/kotlin/app/revanced/patches/youtube/layout/personalinformation/patch/HideEmailAddressPatch.kt

https://github.com/revanced/revanced-integrations/pull/149

feat: hide settings email address

---

src/main/kotlin/app/revanced/patches/youtube/layout/startupshortsreset/fingerprints/UserWasInShortsFingerprint.kt
src/main/kotlin/app/revanced/patches/youtube/layout/startupshortsreset/patch/DisableShortsOnStartupPatch.kt

Closes: https://github.com/revanced/revanced-patches/issues/712

fix(disable-startup-shorts-player): no video shown after invoke new intent from browser

---

src/main/kotlin/app/revanced/patches/youtube/layout/theme/patch/ThemePatch.kt

fix(theme): playlist action bar color

---

src/main/kotlin/app/revanced/patches/music/ad/video/annotations/MusicVideoAdsCompatibility.kt
src/main/kotlin/app/revanced/patches/music/audio/codecs/annotations/CodecsUnlockCompatibility.kt
src/main/kotlin/app/revanced/patches/music/audio/exclusiveaudio/annotations/ExclusiveAudioCompatibility.kt
src/main/kotlin/app/revanced/patches/music/layout/compactheader/annotations/CompactHeaderCompatibility.kt
src/main/kotlin/app/revanced/patches/music/layout/minimizedplayback/annotations/MinimizedPlaybackCompatibility.kt
src/main/kotlin/app/revanced/patches/music/layout/premium/annotations/HideGetPremiumCompatibility.kt
src/main/kotlin/app/revanced/patches/music/layout/tastebuilder/annotations/RemoveTasteBuilderCompatibility.kt
src/main/kotlin/app/revanced/patches/music/layout/upgradebutton/annotations/RemoveUpgradeButtonCompatibility.kt
src/main/kotlin/app/revanced/patches/music/misc/microg/annotations/MusicMicroGPatchCompatibility.kt
src/main/kotlin/app/revanced/patches/music/premium/backgroundplay/annotations/BackgroundPlayCompatibility.kt

Adds `5.27.51`, `5.28.52`, `5.29.52`.

feat: bump YouTube Music patches compatibility

---

src/main/kotlin/app/revanced/patches/youtube/misc/integrations/fingerprints/ServiceFingerprint.kt
src/main/kotlin/app/revanced/patches/youtube/misc/integrations/fingerprints/StandalonePlayerFingerprint.kt
src/main/kotlin/app/revanced/patches/youtube/misc/integrations/patch/IntegrationsPatch.kt

Fixes video player in apps such as Play Store or Sync for Reddit.

fix(youtube/integrations): set context for remaining activities

---

src/main/kotlin/app/revanced/patches/metanav/scaling/annotations/FixScalingCompatibility.kt
src/main/kotlin/app/revanced/patches/metanav/scaling/patch/FixScalingPatch.kt

RFC: This is my first time creating a patch. Does this code seem correct? If not, why?
Here is the intended diff (original on the right):

feat(patch): Fix metaNav Scaling

---

src/main/kotlin/app/revanced/patches/youtube/layout/hideartistcard/annotations/HideArtistCardCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/hideartistcard/patch/HideArtistCardPatch.kt

https://github.com/revanced/revanced-integrations/pull/186

feat: hide artist card

---

src/main/kotlin/app/revanced/patches/youtube/layout/hidealbumcards/annotations/AlbumCardsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/hidealbumcards/fingerprints/AlbumCardsFingerprint.kt
src/main/kotlin/app/revanced/patches/youtube/layout/hidealbumcards/patch/AlbumCardsPatch.kt

https://github.com/revanced/revanced-integrations/pull/184

feat: hide album cards

---

src/main/resources/sponsorblock/host/values/strings.xml

https://github.com/revanced/revanced-integrations/pull/190

Add string skip_automatically_once

---

src/main/kotlin/app/revanced/patches/anytracker/misc/premium/annotations/UnlockPremiumCompatibility.kt
src/main/kotlin/app/revanced/patches/anytracker/misc/premium/fingerprints/CheckPremiumFingerprint.kt
src/main/kotlin/app/revanced/patches/anytracker/misc/premium/patch/UnlockPremiumPatch.kt

Unlocks the premium features of [AnyTracker](https://play.google.com/store/apps/details?id=com.shervinkoushan.anyTracker), such as tracking an unlimited number of items.

feat(anytracker): unlock premium features

---

src/main/kotlin/app/revanced/patches/youtube/misc/zoomhaptics/annotations/ZoomHapticsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/zoomhaptics/fingerprints/ZoomHapticsFingerprint.kt
src/main/kotlin/app/revanced/patches/youtube/misc/zoomhaptics/patch/ZoomHapticsPatch.kt

Disables vibration when zooming videos in YouTube, tested on 17.43.36
https://github.com/revanced/revanced-integrations/pull/217

feat(youtube): `disable-zoom-haptics` patch

---

src/main/kotlin/app/revanced/patches/tiktok/misc/settings/fingerprints/AboutOnClickMethodFingerprint.kt
src/main/kotlin/app/revanced/patches/tiktok/misc/settings/fingerprints/AdPersonalizationActivityOnCreateFingerprint.kt
src/main/kotlin/app/revanced/patches/tiktok/misc/settings/fingerprints/SettingsOnViewCreatedFingerprint.kt
src/main/kotlin/app/revanced/patches/tiktok/misc/settings/patch/TikTokSettingsPatch.kt

https://github.com/orgs/revanced/discussions/734

fix(tiktok): add compatibility for new version

---

src/main/kotlin/app/revanced/patches/tiktok/misc/loginfallback/annotations/TikTokWebLoginCompatibility.kt
src/main/kotlin/app/revanced/patches/tiktok/misc/loginfallback/fingerprints/GoogleAuthAvailableFingerprint.kt
src/main/kotlin/app/revanced/patches/tiktok/misc/loginfallback/fingerprints/GoogleOneTapAuthAvailableFingerprint.kt
src/main/kotlin/app/revanced/patches/tiktok/misc/loginfallback/patch/TikTokLoginFallbackPatch.kt

Fix the issue that user can not login with google. With this patch, Tiktok revanced user can login with google from browser.

feat(tiktok): login with google by web auth.

---

src/main/kotlin/app/revanced/patches/youtube/misc/video/speed/custom/fingerprints/SpeedArrayGeneratorFingerprint.kt

Fixes the fingerprint not working by adding `@FuzzyPatternScanMethod`.

fix(youtube/custom-video-speed): add fuzzy scan

---

src/main/kotlin/app/revanced/patches/twitch/ad/audio/patch/AudioAdsPatch.kt
src/main/kotlin/app/revanced/patches/twitch/ad/video/patch/VideoAdsPatch.kt
src/main/kotlin/app/revanced/patches/twitch/chat/antidelete/fingerprints/ChatUtilCreateDeletedSpanFingerprint.kt
src/main/kotlin/app/revanced/patches/twitch/chat/antidelete/patch/ShowDeletedMessagesPatch.kt
src/main/kotlin/app/revanced/patches/twitch/debug/patch/DebugModePatch.kt

This is the last PR I have queued up for the Twitch settings patch.
I combined it into one PR because the changes per patch are minor.

feat(twitch): add settings support for existing patches

---

docs/4_structure_and_conventions.md

docs: fix styling of tree branch, fix typo

---

src/main/kotlin/app/revanced/patches/anytracker/misc/premium/fingerprints/IsPurchasedFlowFingerprint.kt
src/main/kotlin/app/revanced/patches/anytracker/misc/premium/patch/UnlockPremiumPatch.kt

Fixes the `anytracker` patch by using a working patch. I think the fingerprint might be a bit too fragile, but it works for now.

fix(anytracker) use working patch

---

src/main/kotlin/app/revanced/patches/shared/settings/preference/impl/ArrayResource.kt
src/main/kotlin/app/revanced/patches/shared/settings/resource/patch/AbstractSettingsResourcePatch.kt
src/main/kotlin/app/revanced/patches/twitch/ad/embedded/annotations/EmbeddedAdsCompatibility.kt
src/main/kotlin/app/revanced/patches/twitch/ad/embedded/fingerprints/CreateUsherClientFingerprint.kt
src/main/kotlin/app/revanced/patches/twitch/ad/embedded/patch/EmbeddedAdsPatch.kt
src/main/kotlin/app/revanced/patches/twitch/ad/shared/util/AbstractAdPatch.kt
src/main/kotlin/app/revanced/patches/twitch/ad/video/fingerprints/GetReadyToShowAdFingerprint.kt
src/main/kotlin/app/revanced/patches/twitch/ad/video/patch/VideoAdsPatch.kt
src/main/kotlin/app/revanced/patches/twitch/misc/settings/bytecode/patch/SettingsPatch.kt

Depends on:
- https://github.com/revanced/revanced-patcher/issues/126
(cherry picked from commit 641d33fc7e213031124491bb468fb382267769aa)

feat(twitch): `block-embedded-ads` patch support

---

src/main/kotlin/app/revanced/patches/youtube/layout/homepage/breakingnews/annotations/BreakingNewsCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/layout/homepage/breakingnews/bytecode/fingerprints/BreakingNewsFingerprint.kt
src/main/kotlin/app/revanced/patches/youtube/layout/homepage/breakingnews/bytecode/patch/BreakingNewsPatch.kt
src/main/kotlin/app/revanced/patches/youtube/layout/homepage/breakingnews/resource/patch/BreakingNewsResourcePatch.kt

https://github.com/revanced/revanced-integrations/pull/258

feat: hide breaking news shelf

---

src/main/kotlin/app/revanced/patches/youtube/ad/general/resource/patch/GeneralAdsResourcePatch.kt

https://github.com/revanced/revanced-integrations/pull/257

feat(youtube/general-ads-patch): hide subscribers channel bar

---

.github/workflows/release.yml

RE: https://github.com/semantic-release/github/issues/175#issuecomment-484964034

ci: bypass push permission on protected branches with owner PAT

---

src/main/kotlin/app/revanced/patches/nova/prime/annotations/UnlockPrimeCompatibility.kt
src/main/kotlin/app/revanced/patches/nova/prime/fingerprints/UnlockPrimeFingerprint.kt
src/main/kotlin/app/revanced/patches/nova/prime/patch/UnlockPrimePatch.kt

This patch unlocks the full version of Nova Launcher.

feat(nova-launcher): unlock-prime patch

---

src/main/resources/microg/host/values/strings.xml

**Integrations PR:** https://github.com/revanced/revanced-integrations/pull/301

feat(youtube/microg-support): check if microg is running

---

src/main/kotlin/app/revanced/patches/irplus/ad/annotations/IrplusAdsCompatibility.kt
src/main/kotlin/app/revanced/patches/irplus/ad/fingerprints/IrplusAdsFingerprint.kt
src/main/kotlin/app/revanced/patches/irplus/ad/patch/IrplusAdsPatch.kt

This patch removes the bottom ad bar from the app [irplus](https://play.google.com/store/apps/details?id=net.binarymode.android.irplus).

feat(irplus): remove ads patch

---

src/main/kotlin/app/revanced/patches/reddit/ad/banner/annotations/HideBannerCompatibility.kt
src/main/kotlin/app/revanced/patches/reddit/ad/banner/patch/HideBannerPatch.kt
src/main/kotlin/app/revanced/patches/reddit/ad/general/annotations/GeneralAdsCompatibility.kt

- Bump patches compatibility to v2023.05.0
- Hides banner ads from the comment of subreddits.

feat(reddit): `hide-subreddit-banner` patch & bump patches compatibility to `v2023.05.0`

---

src/main/kotlin/app/revanced/patches/yuka/misc/unlockpremium/annotations/UnlockPremiumCompatibility.kt
src/main/kotlin/app/revanced/patches/yuka/misc/unlockpremium/fingerprints/IsPremiumFingerprint.kt
src/main/kotlin/app/revanced/patches/yuka/misc/unlockpremium/fingerprints/YukaUserConstructorFingerprint.kt
src/main/kotlin/app/revanced/patches/yuka/misc/unlockpremium/patch/UnlockPremiunPatch.kt

Unlock premium features of the application yuka excluded the global search

feat(Yuka): Add unlock premium version patch

---

src/main/kotlin/app/revanced/patches/reddit/ad/banner/annotations/HideBannerCompatibility.kt
src/main/kotlin/app/revanced/patches/reddit/ad/general/annotations/GeneralAdsCompatibility.kt

✨🔼 Feature - Reddit - Bump compatibility to `2023.09.1`
Modification of any RVAP output will have 🎯 prefix because it somehow went brokey
| APK name              | Version   | Status                 | Action |
|-----------------------|-----------|------------------------|--------------------------------------------------------------------------------------|
| com.reddit.frontpage  | 2023.06.0 | ✅ Patching successful | 🎯 Skipped due to `2023.08.0` |
| com.reddit.frontpage  | 2023.08.0 | ✅ Patching successful | 🎯 Working as intended, No action should be taken |
| com.reddit.frontpage  | 2023.09.1 | ✅ Patching successful | 🎯 Working as intended, No action should be taken |
| tv.twitch.android.app | 14.7.0   | ❎ Patching failed | 🎯 Custom: ✅`block-audio-ads` ❎ `block-embedded-ads` …

feat(reddit): bump compatibility to `2023.09.1`

---

src/main/kotlin/app/revanced/patches/twitch/debug/annotations/DebugModeCompatibility.kt
src/main/kotlin/app/revanced/patches/twitch/misc/integrations/annotations/IntegrationsCompatibility.kt
src/main/kotlin/app/revanced/patches/twitch/misc/settings/annotations/SettingsCompatibility.kt

fix a very cringe error that I have made in #1736

fix(twitch): "mpatibility" -> "@Compatbility"

---

src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/annotation/ProtobufSpoofCompatibility.kt
src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/fingerprints/ProtobufParameterBuilderFingerprint.kt
src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/patch/ProtobufSpoofPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/fix/playback/patch/SpoofSignatureVerificationPatch.kt
src/main/kotlin/app/revanced/patches/youtube/misc/microg/patch/bytecode/MicroGBytecodePatch.kt

Imported code from Inotia00
I expanded the method signature, and added an additional check to ensure the walked method is what's expected.

feat(youtube/protobuf-spoof): video playback fix

---

build.gradle.kts

Check out [Kotlin releases](https://kotlinlang.org/docs/releases.html#release-details) for details on changelog

chore(kotlin): update jvm to 1.8.10

---

src/main/kotlin/app/revanced/patches/inshorts/ad/annotations/HideAdsCompatibility.kt
src/main/kotlin/app/revanced/patches/inshorts/ad/fingerprints/InshortsAdsFingerprint.kt
src/main/kotlin/app/revanced/patches/inshorts/ad/patch/InshortsAdsPatch.kt

Removes ads from Inshorts app.

feat: inshorts ads patch

---

src/main/kotlin/app/revanced/patches/all/misc/packagename/patch/ChangePackageNamePatch.kt

i opened a new pr instead of #1832 because it used the wrong branch and changing it failed

feat: add shared patch to change the package name

---

src/main/kotlin/app/revanced/patches/youtubevanced/ad/general/patch/HideAdsPatch.kt

https://github.com/revanced/revanced-integrations/pull/355

fix(youtubevanced/hide-ads): remove broken ad filter

---

package-lock.json

*Everything in `package-lock.json` is refreshed, and all dependencies is up-to-date*
**http-cache-semantics**  <4.1.1
Severity: **high**
http-cache-semantics vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-rc47-6667-2j5j

chore: refresh `package-lock.json`

---

src/main/kotlin/app/revanced/patches/spotify/audio/bytecode/patch/DisableCaptureRestrictionBytecodePatch.kt
src/main/kotlin/app/revanced/patches/spotify/audio/fingerprints/DisableCaptureRestrictionAudioDriverFingerprint.kt

fix(spotify/disable-capture-restriction): fix failing patch

---

src/main/kotlin/app/revanced/patches/ticktick/misc/themeunlock/patch/UnlockThemePatch.kt
src/main/kotlin/app/revanced/patches/twelvewidgets/unlock/patch/UnlockPaidWidgetsPatch.kt
src/main/kotlin/app/revanced/patches/twitter/layout/hideviews/patch/HideViewsBytecodePatch.kt

Can be merged after [patcher changes](https://github.com/revanced/revanced-patcher/pull/168) get merged.

chore(patcher): Prepare patches for upcoming breaking patcher fix

---

src/main/kotlin/app/revanced/patches/youtube/layout/hide/shorts/resource/patch/HideShortsComponentsResourcePatch.kt

https://github.com/revanced/revanced-patches/issues/2267

fix(youtube/hide-shorts-components): adjust settings description

---

src/main/kotlin/app/revanced/patches/songpal/badge/fingerprints/CreateTabsFingerprint.kt
src/main/kotlin/app/revanced/patches/songpal/badge/fingerprints/ShowNotificationFingerprint.kt

As already discussed in #2369, I have attempted to make the songpal patches more resilient.

fix(songpal): make patches more resilient

---

src/main/kotlin/app/revanced/patches/syncforreddit/api/patch/ChangeOAuthClientIdPatch.kt

Fixes lexer errors if read file contents has a new-line.

fix(syncforreddit/change-oauth-client-id): trim read file contents

---

src/main/kotlin/app/revanced/patches/reddit/customclients/infinityforreddit/api/fingerprints/GetHttpBasicAuthHeaderFingerprint.kt
src/main/kotlin/app/revanced/patches/reddit/customclients/infinityforreddit/api/patch/ChangeOAuthClientIdPatch.kt

fix(infinityforreddit): use correct method name

---

src/main/kotlin/app/revanced/patches/tiktok/misc/settings/patch/SettingsPatch.kt

The hardcode register cause a problem on tiktok 30.5.2.

fix(tiktok/settings): use dynamic register instead of hardcode one.

---

src/main/kotlin/app/revanced/patches/youtube/layout/hide/general/patch/HideLayoutComponentsPatch.kt

**Depends on:**
- https://github.com/ReVanced/revanced-integrations/pull/448

feat(YouTube - Hide layout components): Hide `chips shelf`

---

src/main/kotlin/app/revanced/patches/all/misc/mitmproxy/patch/MitmProxyPatch.kt
src/main/kotlin/app/revanced/patches/all/misc/network/patch/OverrideCertificatePinningPatch.kt

closes https://github.com/ReVanced/revanced-patches/issues/1813

feat: Add `Override certificate pinning` patch

---

src/main/kotlin/app/revanced/patches/reddit/customclients/infinityforreddit/api/patch/SpoofClientPatch.kt

fix(InfinityForReddit - Spoof client): Constrain patch to last working versions

---

src/main/kotlin/app/revanced/patches/shared/settings/AbstractSettingsResourcePatch.kt

This PR adds the functions to the public abstract settings resource patch.

feat: Publicize abstract settings resource patch

---

src/main/kotlin/app/revanced/patches/youtube/layout/branding/header/PremiumHeadingPatch.kt

Lets users use the non-premium heading even if they have premium.

feat(YouTube - Premium heading): Allow using default heading

---

CONTRIBUTING.md
README.md

<!- Awaiting decoration (if changes are major) -->
This Pull Request merge the latest change from [ReVanced/revanced-branding | `main`](https://github.com/ReVanced/revanced-branding/tree/main)

docs: Update ReVanced Branding

---

src/main/kotlin/app/revanced/patches/youtube/misc/announcements/AnnouncementsPatch.kt

Partially resolves https://github.com/ReVanced/revanced-patches/issues/3168
(The rest is being resolved by https://github.com/ReVanced/revanced-patches/releases/tag/v2.196.0-dev.1)

feat(YouTube - Announcements): Clarify announcements origin in patch description

---

src/main/kotlin/app/revanced/patches/idaustria/detection/root/RootDetectionPatch.kt
src/main/kotlin/app/revanced/patches/idaustria/detection/root/fingerprints/AttestationSupportedCheckFingerprint.kt
src/main/kotlin/app/revanced/patches/idaustria/detection/root/fingerprints/BootloaderCheckFingerprint.kt
src/main/kotlin/app/revanced/patches/idaustria/detection/root/fingerprints/RootCheckFingeprint.kt
src/main/kotlin/app/revanced/patches/idaustria/detection/root/fingerprints/RootCheckFingerprint.kt
src/main/kotlin/app/revanced/patches/idaustria/detection/signature/SpoofSignaturePatch.kt
src/main/kotlin/app/revanced/patches/songpal/badge/RemoveNotificationBadgePatch.kt
src/main/kotlin/app/revanced/util/Utils.kt
src/main/kotlin/app/revanced/util/microg/MicroGBytecodeHelper.kt

Adds support for ID Austria/Digitales Amt version `3.0.2`

feat(Digitales Amt): Bump compatibility to `3.0.2`

---

src/main/kotlin/app/revanced/patches/youtube/layout/theme/ThemeBytecodePatch.kt

Closes https://github.com/ReVanced/revanced-patches/issues/3225

fix(YouTube - Theme): Consistent patch option descriptions

---

src/main/kotlin/app/revanced/patches/twitch/ad/audio/AudioAdsPatch.kt
src/main/kotlin/app/revanced/patches/twitch/ad/embedded/EmbeddedAdsPatch.kt
src/main/kotlin/app/revanced/patches/twitch/ad/video/VideoAdsPatch.kt
src/main/kotlin/app/revanced/patches/twitch/chat/antidelete/ShowDeletedMessagesPatch.kt
src/main/kotlin/app/revanced/patches/twitch/chat/autoclaim/AutoClaimChannelPointsPatch.kt

Continued from #3246 due to accidentally closing the previous pull request
Now supports version `17.0.0` of Twitch.
- the ad patches and “Auto Claim Channel Points” work.
- "show deleted messages" see the mentioned above pull request
For more information see the histories of the pull reqtests mentioned above

feat(Twitch): Support version `17.0.0`

---

src/main/kotlin/app/revanced/patches/twitch/ad/audio/AudioAdsPatch.kt
src/main/kotlin/app/revanced/patches/twitch/ad/embedded/EmbeddedAdsPatch.kt
src/main/kotlin/app/revanced/patches/twitch/ad/video/VideoAdsPatch.kt
src/main/kotlin/app/revanced/patches/twitch/chat/antidelete/ShowDeletedMessagesPatch.kt
src/main/kotlin/app/revanced/patches/twitch/chat/autoclaim/AutoClaimChannelPointsPatch.kt

Now supports version `17.1.0` of Twitch.
- All advertising and chat patches continue to work.

feat(Twitch): Support version `17.1.0`

---

src/main/kotlin/app/revanced/patches/youtube/layout/branding/CustomBrandingPatch.kt

I hope there isn't anything else I need to change

feat(YouTube - Custom branding): Add "YT ReVanced" to the default app name options

---

src/main/kotlin/app/revanced/patches/spotify/layout/theme/CustomThemePatch.kt

fix(Spotify - Custom Theme): Make description more precise
